## Universidad Tecnológica Nacional
### Facultad Regional Concepción del Uruguay
**Ciencia de Datos**
***
# Trabajo práctico integrador
## Sistema recomendador
***
**Alumno:** Luciano Emmanuel Davezac
**Repositorio:** https://github.com/EmmaDavezac/Sistema-Recomendador-Ciencia-De-Datos


## Problema
* El trabajo práctico integrador es un trabajo de desarorllo en el que se deberán implementar la metodología CRISP-DM para diseñar un sistema recomendador de algún item de interés para el grupo, como pueden ser libros, revistas, artículos de consumo, o cualquier otro. 

* Supongan un comitente vendedor de estos items a través de una plataforma virtual, y su objetivo de negocio es aumentar las ganancias por ventas en un 10% para el año 2026, en contraste con lo vendido en el año 2025. 

* Este comitente les explica que tiene su sistema desarrollado sobre una web, con un carrusel que muestra a los usuarios un numero de artículos que pueden ser de su interés, y que actualmente muestra artículos aleatorios. El comitente también manifiesta que “hace 25 años que vende los mismos 100 artículos, y que esto no va a cambiar, que por cábala siempre vende 100, no hay forma de que se agreguen items nuevos”. No obstante, también “recibe muchos usuarios nuevos todo el tiempo y que, a ojo de buen cubero, compran siempre alrededor de 7 u 8 artículos cada uno, a lo sumo algunos comprarán 10, pero puede cambiar en cualquier momento, si la situación mejora”.

* Ya que no existe ningún sistema pre-existente, no se cuenta con una base de datos, por lo que se deberá diseñar una que guarde datos de los usuarios, datos de los items y las preferencias. El comitente les manifiesta que no tiene ni idea de estas cosas, y confía en su experticia para hacerlo. 

* Los desarrolladores de la web les proporciona la definición de una API que deberán construir, la cual se adjunta.Cualquier inconveniente o información que necesiten saber, el comitente siempre está disponible para consulta, a través del correo electrónico **gd.rottoli@gmail.com**

## Consigna y condiciones de entrega
1. Construir un sistema que permita:
    * Agregar nuevos usuarios.
    * Recomendar, para un usuario determinado, un conjunto de items
    * Registrar las preferencias de los usuarios por los items.
2. Deberán considerar:
    * ¿Qué tipo de sistema recomendador usarán?
    * ¿Cómo medirán y almacenarán las preferencias?
    * Los usuarios y los items, ¿deberán ser descriptos de alguna forma en particular?¿con qué atributos?
    * ¿Cómo harán las recomendaciones para un nuevo usuario (cold start)?
3. Presentar:
    * Servicio funcional con interfaz REST según la especificación brindada, en un repositorio GIT. Usar el lenguaje de programación que prefieran, pero bien documentado. No hace falta que construyan interfaz gráfica, mientras funcionen las llamadas REST. 
    * Documentación de CRISP-DM completa. En la sección de conocimiento de los datos, se  analizarán los datos que deberán ser almacenados. En la sección preparación de los datos, se determinarán los procesos que deberán ser realizados para obtener los datos de la base de datos y las transformaciones necesarias.
    * Base de datos con datos con items de ejemplo y algunos usuarios para probar. 

**Primeros pasos:**
Debe leer el archivo **README.md** para más informacion sobre como ejecutar este proyecto,este archivo incluye:
* Breve resumen del proyecto.
* Requisitos previos necesarios.
* Instrucciones sobre como ejecutar el proyecto.

In [ ]:

#Instalamos las dependencias necesarias, las mismas se encuentran en el archivo requirements.txt.
# Usamos un entorno virtual para evitar conflictos con otras librerías instaladas en el sistema.
%pip install -r requirements.txt

# CRISP-DM
Para resolver esta problematica, utilizaremos la metodología CRISP-DM ya que necesitamos un proceso estructurado que garantice resultados alineados con el negocio.
A lo largo de este documento, se abordarán las seis fases de la metodología:
1. Entendimiento del negocio
2. Entendimiento de los datos
3. Preparación de los datos
4. Modelado
5. Evaluación
6. Implementación

Sin mas que decir, procedemos al desarrollo

# **1.Entendimiento del negocio**
## Objetivos de Negocio
El principal objetivo del negocio, es aumentar las ganancias por ventas en un 10% para el año 2026, en contraste con lo vendido en 2025.

## Problema
El sistema actual muestra artículos aleatorios en un carrusel. 

## **Objetivo de la minería de datos**
Se necesita diseñar e implementar un Sistema Recomendador que sugiera ítems de interés para cada usuario, reemplazando la lógica aleatoria por una predictiva. Esto busca mejorar la experiencia del usuario y, consecuentemente, aumentar la tasa de conversión y el volumen de ventas, alineándose con el objetivo de negocio.

## Criterios de éxito de la minería de Datos
Para validar si el sistema recomendador es apto para su despliegue y cumple con los objetivos del negocio, se definen los siguientes criterios técnicos basados en el rendimiento del modelo frente a la implementacion actual que es al azar:

1.  **La Precision debe ser al menos 3 veces superior a la probabilidad de acierto aleatorio.**
    Dado que contamos con 100 ítems fijos, la probabilidad de acertar un ítem por azar es del 1%. Un modelo con una Precision superior al 3% ya demuestra una capacidad predictiva significativa que justifica su implementación frente al sistema actual.

2.  **Lograr un Recall superior al 10%.**
    El sistema debe ser capaz de identificar al menos una décima parte de las preferencias reales del usuario dentro de un listado acotado de recomendaciones, asegurando que el carrusel no pierda por completo los intereses del cliente.

3.  **Obtener un F1-Score por encima de 0.05.**
    Esta métrica garantiza que el modelo mantiene un balance saludable entre precisión y cobertura, evitando sesgos extremos.

4.  **El tiempo de respuesta de recomendación por usuario debe ser inferior a 300ms.**
    Para no afectar la experiencia de usuario en la web, el motor debe calcular las sugerencias en milisegundos.

## Consideraciones

* **Items Fijos:** El comitente solo vende 100 artículos y no se agregarán ítems nuevos ("por cábala siempre vende 100").Por lo que la cantidad de items es fija.
* **Usuarios Nuevos:** La plataforma recibe "muchos usuarios nuevos todo el tiempo", lo que obliga a tener una estrategia robusta de recomendación inicial (Cold Start).
* **Volumen de Compra:** Los usuarios compran en promedio 7 u 8 artículos, a lo mucho 10.
* **Ausencia de Datos:** No existe una base de datos preexistente, por lo que se debe diseñar e implementar una para almacenar usuarios, ítems y preferencias.
* **Items Genericos:** El comitente no nos especifica los items, los deja a nuestra interpretación, siempre que el sistema funciona

# **2.Entendimiento de los datos**
## Datos a Almacenar
Dado que no hay una base de datos existente, debemos diseñar una que modele las entidades y relaciones del sistema.
Debemos almacenar:
* **Usuarios:** En la documentación de la API suministrada por el comitente se espeficifica que debe tener los atributos:
    * *id* que es el identificador de tipo *integer*
    * *username* que es el nombre de usuario de tipo *string*
    `ejemplo: jgonzalez01@mail.com`
Ademas definimos los siguientes atributos:
    * *telephone* : Numero de telefono del usuario.
    `ejemplo: 0114501100`
    * *birthdate*:Fecha de nacimiento del usuario.
    `ejemplo: 5/15/1985`
    * *gender*: Genero del usuario. Valores validos: "F","M", "X" o null
    * *created_at*:Fecha de registro del usuario.
    `ejemplo: 5/15/2024`

* **Items:** En la documentación suministrada por el comitente se espeficifica que siempre habra exactamente 100 items y que cada uno debe tener los atributos:
    * *id*: es el identificador de tipo *integer*
    * *name*: es el nombre del item de tipo *string*
    `ejemplo: Las mil y una noches`
Ademas definimos los siguientes atributos:
    * *price* : precio del producto de tipo *float*
    `ejemplo: 15.99`
    * *category*: categoria a la que pertenece el producto de tipo *string*.
    `ejemplo: Ficción Fantástica`
    * *description*: descripción del problema de tipo *string*.
    `ejemplo: La historia del encuentro fortuito entre un joven pastor y la última criatura legendaria.`

* **Preferencias de los usuarios por los items:** El comitente nos deja este apartado a nuestro parecer. Diseñamos almacerlas en una entidad llamada "Preferences", que registra el rating que le da un usuario a un item que compro", que almacene los atributos:
    * *user_id* que es el identificador del usuario de tipo *integer*
    * *item_id* que es el identificador del item de tipo *integer*
    * *preference_value*: la ponderación (rating) que le da un usuario al item que compro. Es de tipo *integer* y tiene un valor entre 1 y 5. Luego de comprar un item, el usuario lo reseña indicando que le parecio el item a traves de estrellas, como lo hacen plataformas parecias como Mercado Libre.
Todos los datos anteriores son necesarios para que funcione el sistema a implementar, son los datos minimos necesarios y en caso de que quieran añadirse mas datos el sistema debera ser rediseñado.
## Implementación de la persistencia de datos
Se diseñó una base de datos SQLite (*recommendation_system.db*) para almacenar las tres entidades principales del sistema.
Las razones principales por la que elegimos SQLite en lugar sobre otras opciones son su ligereza, portabilidad y facilidad de uso, ya que no requiere un servidor, se ejecuta como una biblioteca en el mismo proceso de la aplicación, almacena la base de datos en un único archivo, y es ideal para prototipos o para ejecutar localmente sin conexión a internet.

### Codigo SQL para la creacion de las tablas
**Tabla users**
 ```SQL
 CREATE TABLE IF NOT EXISTS users (
                                    id INTEGER PRIMARY KEY,
                                    username VARCHAR(255) NOT NULL UNIQUE,
                                    telephone VARCHAR(50),
                                    birthdate DATE,
                                    gender CHAR(1) CHECK (gender IN ('F', 'M', 'X') OR gender IS NULL),
                                    created_at DATE DEFAULT CURRENT_DATE
                                   );
 ```
**Tabla items**
 ```SQL
CREATE TABLE IF NOT EXISTS items (
                                    id INTEGER PRIMARY KEY,
                                    name VARCHAR(255) NOT NULL,
                                    price FLOAT NOT NULL,
                                    category VARCHAR(100),
                                    description TEXT
                                );
 ```
 **Tabla preferences**
 ```SQL
 CREATE TABLE IF NOT EXISTS preferences (
                user_id INTEGER NOT NULL,
                item_id INTEGER NOT NULL,
                preference_value INTEGER NOT NULL,
                PRIMARY KEY (user_id, item_id),
                FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
                FOREIGN KEY(item_id) REFERENCES items(id) ON DELETE CASCADE
            );

 ```
### Prevención ante valores perdidos
Prevenimos valores perdidos mediante al momento de crear la base de datos utilizano los constraint:
* **NOT NULL**: Es para evitar que datos importantes tomen el valor *null*.
* **ON DELETE CASCADE**: Es para no tener preferencias con referencias nulas que generen inconsistencias en el modelo. Al eliminarse un usuario, se eliminan todas las preferencias de este.
### Comprobacion de la integridad de los datos
* **CHAR(1) CHECK (gender IN ('F', 'M', 'X') OR gender IS NULL)**: Asegura que gender siempre tenga valores validos.


Cargamos los datos desde los CSVs usando la libreria Pandas

# **3.Preparación de los datos**


Una vez lista la base de datos obtemos los datos desde la misma para crear las estructuras necesarias para el modelo

## Creacion de los dataframes 
Obtenemos la informacion de las tablas y creamos los dataframes.
Decidimos crear 3 dataframes , el principal que tendria la informacion de las preferencias y dos auxiliares con la informacion completa de los usuarios y los items.
Decidimos esto ya que trabajar con un solo dataset con toda la informacion aumentaria demasiao la redundancia y el dataset seria muy dificil de manejar.

### **Creacion del dataframe principal** 
Formamos un dataframe uniendo las tablas items y preferences de la base de datos mediante una consulta SQL, este dataframe tendra la informacion de las preferencias junto al nombre del item.
Cada fila del DataFrame resultante contendrá el item_id, name, user_id y preference_value
Este dataframe sera el que utilizara el sistema recomendador.
Aqui hacemos integracion porque juntamos la informacion de dos tablas.

Obtenemos la informacion desde la base de datos
En este caso usamos SQLite como base de datos, pero se puede usar cualquier otra base de datos relacional.Solo es necesario cambiar la librería de conexión y la cadena de conexión.


In [11]:
import sqlite3 #Librería para manejar bases de datos SQLite
import pandas as pd #Librería para manejo de datos
DB_NAME = 'recommendation_system.db'# Nombre del archivo de la base de datos SQLite
#Consulta SQL para unir items y preferences
SQL_QUERY = """
SELECT 
    T1.id as item_id,
    T1.name,
    T2.user_id,
    T2.preference_value

FROM 
    items AS T1 
INNER JOIN 
    preferences AS T2
ON 
    T1.id = T2.item_id;
"""
    
conn = sqlite3.connect(DB_NAME)# Abrimos la conexión a la base de datos
df = pd.read_sql_query(SQL_QUERY, conn)# Leemos las preferencias uniendo items y preferences
df.head()# Mostramos las primeras filas del DataFrame resultante

,item_id,name,user_id,preference_value
0,55,Meteoritos y Cometas,1,4
1,82,Egipto Faraónico,1,4
2,10,Biografía de Marie Curie,1,2
3,33,Gestión de Proyectos PMP,1,5
4,91,Robots en el Tiempo,1,3


### DataFrame de usuarios
A su vez creamos un DataFrame solo con los usuarios desde la base de datos.
El dataframe users_df tiene la información de los usuarios

Obtenemos la informacion desde la base de datos

In [17]:
users_df = pd.read_sql_query("SELECT * FROM users", conn)# Leemos los usuarios desde la base de datos
users_df.head()# Mostramos las primeras filas del DataFrame de usuarios

,id,username,telephone,birthdate,gender,created_at
0,1,jgonzalez01@mail.com,1145011001,5/15/1985,F,1/10/2024
1,2,mrodriguez02@mail.com,1145011002,11/20/1992,M,1/10/2024
2,3,pperez03@mail.com,1145011003,3/1/2000,X,1/10/2024
3,4,llopez04@mail.com,1145011004,7/25/1978,F,1/10/2024
4,5,acarcia05@mail.com,1145011005,9/12/1995,M,1/10/2024


### DataFrame de items
A su vez creamos un DataFrame solo con los items desde la base de datos
El dataframe items_df tiene la información de los items

Obtenemos la informacion desde la base de datos

In [18]:
items_df = pd.read_sql_query("SELECT * FROM items", conn)# Leemos los items desde la base de datos
items_df.head()# Mostramos las primeras filas del DataFrame de items

,id,name,price,category,description
0,1,Crónicas de la Sombra,15.99,Ficción Fantástica,Una épica aventura en un mundo donde la luz se...
1,2,El Jardín Silencioso,22.50,Novela Histórica,Una conmovedora historia ambientada en la posg...
2,3,Guía de Inversión Inteligente,35.00,Economía y Finanzas,Inspirado en las enseñanzas sobre el value inv...
3,4,Recetas de la Abuela,18.75,Cocina,Compendio de platos tradicionales transmitidos...
4,5,Atlas Mundial Actualizado,49.99,Geografía,Cartografía detallada y datos geopolíticos del...


In [19]:
conn.close()# Cerramos la conexión a la base de datos

## Limpieza de los datos


### Dataframe principal
Eliminaremos los valores nulos

In [21]:
df.info()# Mostramos información del DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


Necesitamos que todas las filas tengan toda la informacion, por lo tanto eliminamos las que tengan al menos algun valor nulo.

In [24]:
df.dropna(inplace=True)# Eliminamos filas con valores nulos
df.info()# Mostramos información del DataFrame después de eliminar nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


Eliminamos las filas duplicadas segun las columnas item_id y user_id, la combinacion item-usuario debe ser unica

In [44]:

df.drop_duplicates(subset=['item_id', 'user_id'], inplace=True) # Eliminamos filas duplicadas
df.info()# Mostramos información del DataFrame después de eliminar duplicados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


Eliminamos referencias a usuarios e items que no existen en las tablas correspondientes

In [45]:
#Eliminamos referencias a usuarios e items que no existen en las tablas correspondientes
valid_user_ids = set(users_df['id'])# Obtenemos los IDs de usuarios válidos
valid_item_ids = set(items_df['id'])# Obtenemos los IDs de items válidos
df = df[df['user_id'].isin(valid_user_ids) & df['item_id'].isin(valid_item_ids)]# Filtramos el DataFrame
df.info()# Mostramos información del DataFrame después de eliminar referencias inválidas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


In [48]:
#Eliminamos las filas con valor de preferencia fuera del rango 1-5
df = df[(df['preference_value'] >= 1) & (df['preference_value'] <= 5)]# Filtramos el DataFrame
df.info()# Mostramos información del DataFrame después de eliminar valores fuera de rango

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


### Dataframe usuarios

In [25]:
users_df.info()# Mostramos información del DataFrame de usuarios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          700 non-null    int64 
 1   username    700 non-null    object
 2   telephone   700 non-null    object
 3   birthdate   700 non-null    object
 4   gender      700 non-null    object
 5   created_at  700 non-null    object
dtypes: int64(1), object(5)
memory usage: 32.9+ KB


Eliminamos filas con valores nulos en las columnas id y username en el DataFrame de usuarios

In [27]:
users_df['id'].dropna(inplace=True)# Eliminamos filas con valores nulos en la columna 'id'
users_df['username'].dropna(inplace=True)# Eliminamos filas con valores nulos en la columna 'username'
users_df.info()# Mostramos información del DataFrame de usuarios después de eliminar nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          700 non-null    int64 
 1   username    700 non-null    object
 2   telephone   700 non-null    object
 3   birthdate   700 non-null    object
 4   gender      700 non-null    object
 5   created_at  700 non-null    object
dtypes: int64(1), object(5)
memory usage: 32.9+ KB


Verificamos si hay usuarios duplicados segun la columna id y la columna username

In [29]:
users_df.duplicated(subset=['id']).sum()# Verificamos si hay usuarios duplicados en la columna 'id'
users_df.duplicated(subset=['username']).sum()# Verificamos si hay usuarios duplicados en la columna 'username'
users_df.drop_duplicates(subset=['id'], inplace=True)# Eliminamos usuarios duplicados según la columna 'id'
users_df.drop_duplicates(subset=['username'], inplace=True)# Eliminamos usuarios duplicados según la columna 'username'
users_df.info()# Mostramos información del DataFrame de usuarios después de eliminar duplicados

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   id          700 non-null    int64 
 1   username    700 non-null    object
 2   telephone   700 non-null    object
 3   birthdate   700 non-null    object
 4   gender      700 non-null    object
 5   created_at  700 non-null    object
dtypes: int64(1), object(5)
memory usage: 32.9+ KB


### Dataframe items

In [35]:
items_df.info()# Mostramos información del DataFrame de usuarios

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           100 non-null    int64  
 1   name         100 non-null    object 
 2   price        100 non-null    float64
 3   category     100 non-null    object 
 4   description  100 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB


Eliminamos filas con valores nulos en las columnas id

In [36]:
items_df['id'].dropna(inplace=True)# Eliminamos filas con valores nulos en la columna 'id'
items_df.info()# Mostramos información del DataFrame de items después de eliminar nulos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           100 non-null    int64  
 1   name         100 non-null    object 
 2   price        100 non-null    float64
 3   category     100 non-null    object 
 4   description  100 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB


## Transformacion de los datos

### Dataframe principal

Acomodamos los tipos de cada columna

In [42]:
df.info()# Mostramos información del DataFrame

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


In [43]:
df['item_id'] = df['item_id'].astype(int)# Convertimos la columna 'item_id' a tipo entero
df['name'] = df['name'].astype(str)# Convertimos la columna 'name' a tipo cadena de texto
df['user_id'] = df['user_id'].astype(int)# Convertimos la columna 'user_id' a tipo entero
df['preference_value'] = df['preference_value'].astype(int)# Convertimos la columna 'preference_value' a tipo entero
df.info()# Mostramos información del DataFrame después de conversiones de tipo

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5666 entries, 0 to 5665
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype 
---  ------            --------------  ----- 
 0   item_id           5666 non-null   int64 
 1   name              5666 non-null   object
 2   user_id           5666 non-null   int64 
 3   preference_value  5666 non-null   int64 
dtypes: int64(3), object(1)
memory usage: 177.2+ KB


### Dataframe usuarios

Acomodamos los tipos de cada columna

In [37]:
users_df.info()# Mostramos información del DataFrame de items

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 700 entries, 0 to 699
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype         
---  ------      --------------  -----         
 0   id          700 non-null    int64         
 1   username    700 non-null    object        
 2   telephone   700 non-null    object        
 3   birthdate   700 non-null    datetime64[ns]
 4   gender      700 non-null    object        
 5   created_at  700 non-null    datetime64[ns]
dtypes: datetime64[ns](2), int64(1), object(3)
memory usage: 32.9+ KB


In [ ]:
users_df['id'] = users_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
users_df['username'] = users_df['username'].astype(str)
users_df['telephone'] = users_df['telephone'].astype(str)# Aseguramos que la columna 'telephone' sea de tipo string
users_df['birthdate'] = pd.to_datetime(users_df['birthdate'])# Convertimos la columna 'birthdate' a tipo datetime
users_df['gender'] = users_df['gender'].astype(str)# seguramos que la columna 'gender' sea de tipo string
users_df['created_at'] = pd.to_datetime(users_df['created_at'])# Convertimos la columna 'created_at' a tipo datetime
users_df.info()# Mostramos información del DataFrame de usuarios después de cambiar tipos de datos

### Dataframe items

In [38]:
items_df.info()# Mostramos información del DataFrame de items

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           100 non-null    int64  
 1   name         100 non-null    object 
 2   price        100 non-null    float64
 3   category     100 non-null    object 
 4   description  100 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB


Acomodamos los tipos de cada columna

In [41]:
items_df['id'] = items_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
items_df['name'] = items_df['name'].astype(str)# Aseguramos que la columna 'name' sea de tipo string
items_df['price'] = items_df['price'].astype(float)# Aseguramos que la columna 'price' sea de tipo float
items_df['category'] = items_df['category'].astype(str)# Aseguramos que la columna 'category' sea de tipo string
items_df['description'] = items_df['description'].astype(str)# Aseguramos que la columna 'description0' sea de tipo string
items_df.info()# Mostramos información del DataFrame de items después de cambiar tipos de datos

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   id           100 non-null    int64  
 1   name         100 non-null    object 
 2   price        100 non-null    float64
 3   category     100 non-null    object 
 4   description  100 non-null    object 
dtypes: float64(1), int64(1), object(3)
memory usage: 4.0+ KB


# *4.Modelado*
## Selección de técnica de modelado
Construiremos dos sistemas recomendadores de filtrado colaborativo: uno basado en usuarios y otro en items.
Evaluaremos ambos sistemas y compararemos sus resultados, luego seleccionaremos el mejor para su implementación final.

## Modelo filtro colaborativo basado en usuarios.
Utilizaremos la similitud entre usuarios en función de sus preferencias para realizar recomendaciones. Recordemos que como hipótesis tenemos que usuarios similares tienden a gustarle items similares.
Los pasos a seguir son los siguientes:

1. Encontrar usuarios similares en función de los ratings que han dado a los productos de la base de datos.
2. Identificar los items que usuarios similares han ranqueado alto, y los usuarios no han consumido
3. Recomendar items en función de este ranking.

### Construcción del modelo
#### Matriz de preferencias
Vamos a crear un amatriz Usuario x Item con el puntaje dado por cada usuario a cada item que compro. Es una matriz dispersa por la que habrá muchos valores nulos.

In [49]:
matrix = df.pivot_table(index='user_id', columns='name', values='preference_value')# Creamos la matriz usuario-item
matrix.head()

name,Agujeros Negros,Algoritmos Avanzados en Java,Aromaterapia,Asesinato en el Tren Nocturno,Atlas Mundial Actualizado,Bases de Datos SQL,Biografía de Marie Curie,Bolsa de Valores Avanzada,Caligrafía Japonesa,Cartas de Amor Perdidas,...,Sin Rastro,Sonetos al Mar,Sueños de Androides,Tapas Españolas,Testigo Ocular,Versos Olvidados,Voces de la Guerra Civil,Yoga Aéreo,Yoga para Principiantes,Época Medieval
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,2.0,NaN,NaN,NaN,...,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,4.0,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,3.0,NaN,NaN,5.0,NaN,NaN,5.0,NaN
3,NaN,NaN,NaN,NaN,3.0,NaN,NaN,NaN,2.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,5.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,2.0,NaN,NaN,4.0,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0


Hay personas que tienden a dar un puntaje mayor que otras, por lo que normalizaremos los valores. 
Hacemos que todos los puntajes tengan la misma media (0) y la misma desviación estandar (1)
Luego de la normalización, los valores negativos corresponden a las puntuaciones que un usuario da por debajo de su promedio.

In [50]:

user_item_matrix = matrix.copy()# hacemos una copia para trabajar sin alterar la original
row_mean = user_item_matrix.mean(axis=1)# Calculamos el promedio por fila
row_std = user_item_matrix.std(axis=1)# Calculamos la desviación estándar por fila
row_std[row_std == 0] = 1 # Evitamos división por cero
matrix_norm = user_item_matrix.sub(row_mean, axis=0).div(row_std, axis=0)# Normalizamos la matriz usuario-item
matrix_norm.head()

name,Agujeros Negros,Algoritmos Avanzados en Java,Aromaterapia,Asesinato en el Tren Nocturno,Atlas Mundial Actualizado,Bases de Datos SQL,Biografía de Marie Curie,Bolsa de Valores Avanzada,Caligrafía Japonesa,Cartas de Amor Perdidas,...,Sin Rastro,Sonetos al Mar,Sueños de Androides,Tapas Españolas,Testigo Ocular,Versos Olvidados,Voces de la Guerra Civil,Yoga Aéreo,Yoga para Principiantes,Época Medieval
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,-1.106797,NaN,NaN,NaN,...,0.474342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,0.380319,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.253546,NaN,NaN,1.014185,NaN,NaN,1.014185,NaN
3,NaN,NaN,NaN,NaN,-0.283193,NaN,NaN,NaN,-1.227168,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1.587011,-0.083527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-0.918796,NaN,NaN,0.751742,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.490788


#### Similitud entre usuarios
Usaremos la similitud de coseno para determinar la similitud entre usuarios.
Esto mide el "ángulo" entre los vectores de preferencias de dos usuarios en el espacio de ítems. Un valor cercano a 1 indica alta similitud.

Rellenamos los valores NaN con 0 para calcular similitudes

In [51]:
user_item_matrix_filled = matrix_norm.fillna(0)# Rellenamos los valores NaN con 0
user_item_matrix_filled.head()

name,Agujeros Negros,Algoritmos Avanzados en Java,Aromaterapia,Asesinato en el Tren Nocturno,Atlas Mundial Actualizado,Bases de Datos SQL,Biografía de Marie Curie,Bolsa de Valores Avanzada,Caligrafía Japonesa,Cartas de Amor Perdidas,...,Sin Rastro,Sonetos al Mar,Sueños de Androides,Tapas Españolas,Testigo Ocular,Versos Olvidados,Voces de la Guerra Civil,Yoga Aéreo,Yoga para Principiantes,Época Medieval
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.000000,0.000000,0.000000,0.000000,0.0,-1.106797,0.0,0.000000,0.0,...,0.474342,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2,0.0,0.000000,0.000000,0.380319,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,-0.253546,0.0,0.000000,1.014185,0.0,0.000000,1.014185,0.000000
3,0.0,0.000000,0.000000,0.000000,-0.283193,0.0,0.000000,0.0,-1.227168,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
4,0.0,1.587011,-0.083527,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,-0.918796,0.000000,0.0,0.751742,0.000000,0.000000
5,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,-1.490788


In [52]:
from sklearn.metrics.pairwise import cosine_similarity
user_similarity_cosine = cosine_similarity(user_item_matrix_filled)# Calculamos la similitud del coseno entre los usuarios
user_item_matrix_filled.head()

name,Agujeros Negros,Algoritmos Avanzados en Java,Aromaterapia,Asesinato en el Tren Nocturno,Atlas Mundial Actualizado,Bases de Datos SQL,Biografía de Marie Curie,Bolsa de Valores Avanzada,Caligrafía Japonesa,Cartas de Amor Perdidas,...,Sin Rastro,Sonetos al Mar,Sueños de Androides,Tapas Españolas,Testigo Ocular,Versos Olvidados,Voces de la Guerra Civil,Yoga Aéreo,Yoga para Principiantes,Época Medieval
user_id,,,,,,,,,,,,,,,,,,,,,
1,0.0,0.000000,0.000000,0.000000,0.000000,0.0,-1.106797,0.0,0.000000,0.0,...,0.474342,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
2,0.0,0.000000,0.000000,0.380319,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,-0.253546,0.0,0.000000,1.014185,0.0,0.000000,1.014185,0.000000
3,0.0,0.000000,0.000000,0.000000,-0.283193,0.0,0.000000,0.0,-1.227168,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.000000
4,0.0,1.587011,-0.083527,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,-0.918796,0.000000,0.0,0.751742,0.000000,0.000000
5,0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.000000,0.0,0.000000,0.0,...,0.000000,0.0,0.000000,0.0,0.000000,0.000000,0.0,0.000000,0.000000,-1.490788


Los valores estan en el intervalo [-1, 1], donde valores positivos significan mayor similitud.

#### Matriz de similitud entre usuarios

In [53]:
user_ids = user_item_matrix_filled.index.tolist()# Obtenemos los IDs de usuario
user_similarity = pd.DataFrame( #Creamos la matriz de similitud de usuarios
    user_similarity_cosine, 
    index=user_ids, 
    columns=user_ids
)
user_similarity.index = user_similarity.index.astype(str)# Aseguramos que los índices sean strings
user_similarity.columns = user_similarity.columns.astype(str)# Aseguramos que las columnas sean strings
user_similarity.head()

,1,2,3,4,5,6,7,8,9,10,...,691,692,693,694,695,696,697,698,699,700
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.026530,-0.017687,-0.160947,-0.045985,0.183940,0.201626,0.000000,0.000000,0.000000,-0.074283
2,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.029778,...,-0.034034,0.000000,0.134717,0.008508,0.000000,0.000000,-0.124791,0.000000,0.106356,0.000000
3,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000000,...,0.260813,0.000000,-0.140438,0.000000,-0.015839,-0.041181,0.000000,0.000000,0.133046,0.000000
4,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,-0.014715,...,0.000000,-0.012146,0.000000,-0.311131,-0.227976,0.000000,0.000000,-0.293379,0.000000,0.000000
5,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.286501,...,-0.039416,0.030320,0.000000,-0.018192,0.000000,-0.150083,-0.259234,0.016676,0.183434,0.030320


Dado un usuario

In [56]:

user = "1"

Veamos los items comprados por el mismo

In [58]:
user_items = matrix_norm.loc[int(user)]# Obtenemos las preferencias del usuario
items_comprados = user_items[user_items.notna()].index.tolist()# Items comprados por el usuario
items_comprados

['Biografía de Marie Curie',
 'Cocina Mexicana Auténtica',
 'Cuentos Breves de Otoño',
 'Egipto Faraónico',
 'Gestión de Proyectos PMP',
 'Las Arenas del Tiempo',
 'Meteoritos y Cometas',
 'Principios de Python Moderno',
 'Robots en el Tiempo',
 'Sin Rastro']

Obtenemos los 30 usuarios mas similares a 

In [59]:
n=30
        
similar_users = ( # Obtenemos usuarios similares
        user_similarity[user]
        .sort_values(ascending=False)
        .drop(user, errors='ignore')
        .head(n)
    )
similar_users

21     1.000000
31     1.000000
61     1.000000
51     1.000000
41     1.000000
71     1.000000
81     1.000000
151    1.000000
131    1.000000
101    1.000000
111    1.000000
11     1.000000
171    1.000000
141    1.000000
161    1.000000
121    1.000000
91     1.000000
179    0.241942
263    0.230120
433    0.230120
405    0.230120
419    0.230120
447    0.230120
235    0.230120
207    0.230120
277    0.230120
249    0.230120
221    0.230120
291    0.230120
193    0.230120
Name: 1, dtype: float64

Veamos que items compraron usuarios similares

In [60]:
# items comprados por usuarios similares
#  Obtenemos la lista de IDs de usuarios similares asegurandonos que sean enteros
similar_users_ids = similar_users.index.astype(int).tolist()
print(f"Usuarios similares a {user}: {similar_users_ids}")

## Filtrar matrix_norm para obtener solo las filas de los usuarios similares
# Usamos .loc[] para indexar por las etiquetas del índice (los user_id).
similar_user_items = matrix_norm.loc[similar_users_ids]
# Identificar los ítems que *al menos un* usuario similar ha comprado/calificado
items_comprados_usuarios_similares = similar_user_items.columns[
    similar_user_items.notna().any()
].tolist()

items_comprados_usuarios_similares

Usuarios similares a 1: [21, 31, 61, 51, 41, 71, 81, 151, 131, 101, 111, 11, 171, 141, 161, 121, 91, 179, 263, 433, 405, 419, 447, 235, 207, 277, 249, 221, 291, 193]


['Biografía de Marie Curie',
 'Cocina Mexicana Auténtica',
 'Criptomonedas y Blockchain',
 'Cuentos Breves de Otoño',
 'Egipto Faraónico',
 'Escultura Moderna',
 'Gestión de Proyectos PMP',
 'Guía de Inversión Inteligente',
 'Haikus Japoneses',
 'Las Arenas del Tiempo',
 'Mares y Océanos',
 'Meteoritos y Cometas',
 'Principios de Python Moderno',
 'Renacimiento Cultural',
 'Robots en el Tiempo',
 'Sin Rastro']

Items candidatos para recomendar (Son los items comprados por usuarios similares excluyendo los que el usuario ya compro)

In [61]:
candidate_items = list(set(items_comprados_usuarios_similares) - set(items_comprados))
candidate_items

['Escultura Moderna',
 'Mares y Océanos',
 'Haikus Japoneses',
 'Criptomonedas y Blockchain',
 'Guía de Inversión Inteligente',
 'Renacimiento Cultural']

Vamos a ponderar los items de forma tal que la puntuación sea igual al promedio ponderado entre la similitud del usuario y el rating que le dió ese usuario.
Los usuarios más similares van a pesar más en el rating.

In [62]:
similar_user_preferences = matrix_norm.loc[similar_users_ids]# Preferencias de usuarios similares
items_comprados_por_similares = similar_user_preferences.columns[similar_user_preferences.notna().any()].tolist()# Items comprados por usuarios similares
candidate_items = list(set(items_comprados_por_similares) - set(items_comprados))# Items candidatos para recomendar
candidate_matrix= similar_user_preferences[candidate_items].fillna(0).copy()# Rellenamos NaN con 0
similar_users.index = similar_users.index.astype(candidate_matrix.index.dtype)# Aseguramos que los índices coincidan
weighted_scores = candidate_matrix.multiply(similar_users, axis=0)# Puntuaciones ponderadas
sum_similarity = similar_users.sum()# Suma de similitudes
recommendation_scores = weighted_scores.sum(axis=0) / sum_similarity# Puntuaciones finales
recommendation_scores

name
Escultura Moderna               -0.013793
Mares y Océanos                 -0.037794
Haikus Japoneses                -0.029793
Criptomonedas y Blockchain       0.162760
Guía de Inversión Inteligente    0.162760
Renacimiento Cultural           -0.013793
dtype: float64

Ordenamos las recomendaciones de forma descendente segun su puntuacion

In [63]:
recomendaciones_ordenadas = recommendation_scores.sort_values(ascending=False)# Ordenamos las recomendaciones

##### Recomendaciones

In [64]:
recomendaciones_finales = recomendaciones_ordenadas.index.tolist()# Lista final de recomendaciones
print(f"Items recomendados para el usuario {user}: ")
recomendaciones_finales

Items recomendados para el usuario 1: 


['Guía de Inversión Inteligente',
 'Criptomonedas y Blockchain',
 'Escultura Moderna',
 'Renacimiento Cultural',
 'Haikus Japoneses',
 'Mares y Océanos']

#### Correccion del cold start
El problema del Cold Start se presenta cuando un usuario es nuevo en la plataforma y, por lo tanto, no ha interactuado con ningún ítem. Sin historial de preferencias, el algoritmo de Filtro Colaborativo Basado en Usuarios no puede calcular la similitud con otros usuarios, lo que resulta en la imposibilidad de generar recomendaciones.
Como solucion el sistema aplica una estrategia de recomendación basada en popularidad.
La popularidad de un ítem se mide por el número de veces que ha sido calificado en el historial de preferencias.
Se agrupan las preferencias po ítem y se cuenta el número total de registros para cada uno.
Esta estrategia es eficaz porque asegura que el usuario nuevo sea expuesto a los artículos que han tenido mayor éxito entre la base de usuarios existente, maximizando la probabilidad de una interacción inicial positiva. Una vez que el usuario nuevo realiza una primera calificación, su ID ingresa a la matriz de preferencias y el sistema pasa a usar el modelo principal en futuras solicitudes.

##### Top 10 items mas comprados

In [65]:
n=10
top_items = df.groupby('name')['preference_value'].count().sort_values(ascending=False)# Contamos la cantidad de preferencias por item y los ordenamos
top_items.head(n).index.tolist()# Retornamos los nombres de los items más populares

['Fitness Funcional',
 'Mitología Griega',
 'El Último Dragón',
 'Crimen en la Mansión',
 'Biografía de Marie Curie',
 'Historia del Arte Renacentista',
 'El Misterio de la Calle Nueve',
 'La Ciudad bajo la Niebla',
 'Haikus Japoneses',
 'Ciberseguridad Esencial']

##### Activacion del Cold Start
Se activa en dos escenarios dentro de la función de recomendación principal
1. Usuario sin preferencias: para esto definimos la siguiente funcion

In [66]:
def user_has_preferences(user_id: int) -> bool:
    """Verifica si un usuario tiene preferencias registradas en la matriz normalizada.
    Args:
        user_id (int): ID del usuario a verificar.
    Returns:
        bool: True si el usuario tiene preferencias, False en caso contrario."""
    return user_id in matrix_norm.index
# Ejemplo de uso
user_id = 350 #ya sabemos que este usuario tiene preferencias
if user_has_preferences(user_id):
    print(f"El usuario {user_id} tiene preferencias registradas.")
user_id = 9999 #suponemos que este usuario no existe
if not user_has_preferences(user_id):
    print(f"El usuario {user_id} no tiene preferencias registradas.")

El usuario 350 tiene preferencias registradas.
El usuario 9999 no tiene preferencias registradas.


2. Fallo del modelo principal: El modelo intenta la predicción, pero la suma de similitudes es cero.

### Evaluacion del modelo
Primero encapsulamos el sistema en funciones para simplicidad
Para probar el modelo definimos:
*   La función load_test_data carga los datos de prueba desde los archivos CSV     locales a la base de datos.
    Estos datos se crearon para evaluar los modelos en base a las especificaciones dadas por el comitente. 
    Hay 700 usuarios, 100 items y 5666 preferencias.
Se respeto el punto de que los usuarios compran entre 7 y 10 items cada uno.
*   La funcion initialize_db que crea una base de datos con datos de prueba.
*   La funcion initial_load que obtiene los datos desde la base de datos y los procesa para asegurar la calidad de los datos



In [31]:
import os # Librería para manejo de archivos
import pandas as pd # Librería para manejo de datos
import sqlite3 # Librería para manejar bases de datos SQLite
from sklearn.metrics.pairwise import cosine_similarity # Función para calcular similitud del coseno
DB_NAME = 'recommendation_system.db'# Nombre del archivo de la base de datos SQLite
USERS_URL = './Datasets/Users.csv'# Ruta local del archivo CSV de usuarios
ITEMS_URL = './Datasets/Items.csv'# Ruta local del archivo CSV de items
PREFERENCES_URL = './Datasets/Preferences.csv'# Ruta local del archivo CSV de preferencias
def load_test_data(conn):
    """Carga los datos de prueba desde los archivos CSV locales a la base de datos SQLite."""
    # Cargamos los datos desde los CSV
    users_df = pd.read_csv(USERS_URL)
    items_df = pd.read_csv(ITEMS_URL)
    preferences_df = pd.read_csv(PREFERENCES_URL)
    users_df.to_sql('users', conn, if_exists='append', index=False)# Insertamos los datos de usuarios
    items_df.to_sql('items', conn, if_exists='append', index=False)# Insertamos los datos de items
    preferences_df.to_sql('preferences', conn, if_exists='append', index=False)# Insertamos los datos de preferencias

def initialize_db():
    """
    Crea y puebla la base de datos SOLO si el archivo DB no existe.
    Establece las claves primarias (compuestas) y foráneas.
    """
    try:

        #Conexión a la base de datos (se crea el archivo si no existe)
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        # Crear las tablas con el esquema definido previamente
        # Usamos esto para asegurar que los tipos de datos y restricciones (como el género) se cumplan
        cursor.executescript('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            telephone TEXT,
            birthdate DATE,
            gender TEXT CHECK (gender IN ('F', 'M', 'X') OR gender IS NULL),
            created_at DATE
        );

        CREATE TABLE IF NOT EXISTS items (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            price REAL,
            category TEXT,
            description TEXT
        );

        CREATE TABLE IF NOT EXISTS preferences (
            user_id INTEGER,
            item_id INTEGER,
                            
            preference_value INTEGER,
            PRIMARY KEY (user_id, item_id),
            FOREIGN KEY (user_id) REFERENCES users (id),
            FOREIGN KEY (item_id) REFERENCES items (id)
        );
        ''')
        load_test_data(conn)# Cargamos los datos de prueba desde los CSV locales
        conn.commit()# Guardamos los cambios en la base de datos
          
        print(f" Base de datos SQLite creada y cargada con éxito.")
            
    except Exception as e:
        print(f" Error al inicializar SQLite: {e}")
        raise

def initial_load():
    """Carga los datos de SQLite (una vez que la DB existe y si no, la crea) y genera las matrices necesarias para el sistema recomendador.
    Returns:
        tuple: (df, matrix_norm, user_similarity, users_df, items_df)"""
    if not(os.path.exists(DB_NAME)): # Verificamos si la base de datos ya existe
        print(f"Base de datos '{DB_NAME}' no encontrada. Creandola e inicializándola...")
        initialize_db() #Inicializa la DB si no existe
    
    #Consulta SQL para unir items y preferences
    SQL_QUERY = """
SELECT 
    T1.id as item_id,
    T1.name,
    T2.user_id,
    T2.preference_value

FROM 
    items AS T1 
INNER JOIN 
    preferences AS T2
ON 
    T1.id = T2.item_id;
"""
    
    conn = sqlite3.connect(DB_NAME)# Abrimos la conexión a la base de datos
    df = pd.read_sql_query(SQL_QUERY, conn)# Leemos las preferencias uniendo items y preferences
    users_df = pd.read_sql_query("SELECT * FROM users", conn)# Leemos los usuarios desde la base de datos
    items_df = pd.read_sql_query("SELECT * FROM items", conn)# Leemos los items desde la base de datos
    conn.close()# Cerramos la conexión a la base de datos
    #Procesamos los datos como se hizo anteriormente
    df.dropna(inplace=True)# Eliminamos filas con valores nulos
    df.drop_duplicates(subset=['item_id', 'user_id'], inplace=True) # Eliminamos filas duplicadas
    valid_user_ids = set(users_df['id'])# Obtenemos los IDs de usuarios válidos
    valid_item_ids = set(items_df['id'])# Obtenemos los IDs de items válidos
    df = df[df['user_id'].isin(valid_user_ids) & df['item_id'].isin(valid_item_ids)]# Filtramos el DataFrame (identificamos referencias inválidas)
    df = df[(df['preference_value'] >= 1) & (df['preference_value'] <= 5)]# Filtramos el DataFrame (eliminamos valores fuera de rango)
    df['item_id'] = df['item_id'].astype(int)# Convertimos la columna 'item_id' a tipo entero
    df['name'] = df['name'].astype(str)# Convertimos la columna 'name' a tipo cadena de texto
    df['user_id'] = df['user_id'].astype(int)# Convertimos la columna 'user_id' a tipo entero
    df['preference_value'] = df['preference_value'].astype(int)# Convertimos la columna 'preference_value' a tipo entero
    users_df.dropna(subset=['id'], inplace=True)# Eliminamos filas con valores nulos en las columnas 'id' 
    users_df.dropna(subset=['username'], inplace=True)# Eliminamos filas con valores nulos en la columna 'username'
    users_df.drop_duplicates(subset=['id'], inplace=True)# Eliminamos usuarios duplicados según la columna 'id'
    users_df.drop_duplicates(subset=['username'], inplace=True)# Eliminamos usuarios duplicados según la columna 'username'
    users_df['id'] = users_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
    users_df['username'] = users_df['username'].astype(str)
    users_df['telephone'] = users_df['telephone'].astype(str)# Aseguramos que la columna 'telephone' sea de tipo string
    users_df['birthdate'] = pd.to_datetime(users_df['birthdate'])# Convertimos la columna 'birthdate' a tipo datetime
    users_df['gender'] = users_df['gender'].astype(str)# seguramos que la columna 'gender' sea de tipo string
    users_df['created_at'] = pd.to_datetime(users_df['created_at'])# Convertimos la columna 'created_at' a tipo datetime
    items_df['id'].dropna(inplace=True)# Eliminamos filas con valores nulos en la columna 'id'
    items_df['id'] = items_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
    items_df['name'] = items_df['name'].astype(str)# Aseguramos que la columna 'name' sea de tipo string
    items_df['price'] = items_df['price'].astype(float)# Aseguramos que la columna 'price' sea de tipo float
    items_df['category'] = items_df['category'].astype(str)# Aseguramos que la columna 'category' sea de tipo string
    items_df['description'] = items_df['description'].astype(str)# Aseguramos que la columna 'description0' sea de tipo string

    #Creamos las matrices necesarias para el sistema recomendador
    matrix = df.pivot_table(index='user_id', columns='name', values='preference_value')# Creamos la matriz usuario-item
    user_item_matrix = matrix.copy()# hacemos una copia para trabajar sin alterar la original
    row_mean = user_item_matrix.mean(axis=1)# Calculamos el promedio por fila
    row_std = user_item_matrix.std(axis=1)# Calculamos la desviación estándar por fila
    row_std[row_std == 0] = 1 # Evitamos división por cero
    matrix_norm = user_item_matrix.sub(row_mean, axis=0).div(row_std, axis=0)# Normalizamos la matriz usuario-item
    user_item_matrix_filled = matrix_norm.fillna(0)# Rellenamos los valores NaN con 0 para calcular similitudes
    user_similarity_cosine = cosine_similarity(user_item_matrix_filled)# Calculamos la similitud del coseno entre los usuarios
    user_ids = user_item_matrix_filled.index.tolist()# Obtenemos los IDs de usuario
    user_similarity = pd.DataFrame( #Creamos la matriz de similitud de usuarios
        user_similarity_cosine, 
        index=user_ids, 
        columns=user_ids
    )
    user_similarity.index = user_similarity.index.astype(str)# Aseguramos que los índices sean strings
    user_similarity.columns = user_similarity.columns.astype(str)# Aseguramos que las columnas sean strings
    # Retornamos los datos procesados
    return df, matrix_norm, user_similarity, users_df, items_df,row_mean

try:
    DF, MATRIX_NORM, USER_SIMILARITY, USERS_DF, ITEMS_DF, row_mean = initial_load()#
except Exception as e:# Manejo de errores en la carga inicial
    print(f" ERROR FATAL: La aplicación no pudo iniciar debido al error de carga/procesamiento: {e}")
def user_has_preferences(user_id: int) -> bool:
    """Verifica si un usuario tiene preferencias registradas en la matriz normalizada.
    Args:a
        user_id (int): ID del usuario a verificar.
    Returns:
        bool: True si el usuario tiene preferencias, False en caso contrario."""
    return user_id in MATRIX_NORM.index

def cold_start_items_recommendations(number_max_of_recommendations: int) -> list: 
    """Genera recomendaciones para usuarios nuevos basadas en los items más populares.
    Args:
        number_max_of_recommendations (int): Número máximo de items a recomendar.
    Returns: 
        list: Lista de nombres de items recomendados."""
    top_items = DF.groupby('name')['preference_value'].count().sort_values(ascending=False)# Contamos la cantidad de preferencias por item y los ordenamos
    return top_items.head(number_max_of_recommendations).index.tolist()# Retornamos los nombres de los items más populares

def get_recommendations(user_id: int, number_max_of_recommendations: int) -> list:
    """Genera recomendaciones para un usuario específico, ya sea basado en usuarios similares o en los items más populares si el usuario es nuevo.
    Args:
        user_id (int): ID del usuario para el cual se generan recomendaciones.
        number_max_of_recommendations (int): Número máximo de items a recomendar.
    Returns:
        list: Lista de nombres de items recomendados.
    """
    K_NEIGHBORS = 50 # Número usuarios similares a considerar
    if user_has_preferences(user_id): # Verificamos si el usuario tiene preferencias
        user_id_str = str(user_id)
        user_items = MATRIX_NORM.loc[user_id]
        items_comprados = user_items[user_items.notna()].index.tolist()

        # Calculamos la media del usuario objetivo a partir del DataFrame de preferencias.
        user_mean_rating = DF[DF['user_id'] == user_id]['preference_value'].mean()
        if pd.isna(user_mean_rating):
             # Fallback: si no se encuentra, usamos el valor neutro 3.0 
             # esto lo hacemos para evitar problemas en la predicción
             #esto no debería ocurrir si el usuario tiene preferencias
            user_mean_rating = 3.0 
        
        similar_users = (
            USER_SIMILARITY[user_id_str]
            .sort_values(ascending=False)
            .drop(user_id_str, errors='ignore')
            .head(K_NEIGHBORS)
        )
        similar_users_ids = similar_users.index.astype(int).tolist()
        sum_similarity = similar_users.sum()
        
        if similar_users.empty or sum_similarity == 0:
            return cold_start_items_recommendations(number_max_of_recommendations)
        
        similar_user_preferences = MATRIX_NORM.loc[similar_users_ids]
        items_comprados_por_similares = similar_user_preferences.columns[
            similar_user_preferences.notna().any()
        ].tolist()
        candidate_items = list(set(items_comprados_por_similares) - set(items_comprados))
        
        if not candidate_items:
            return cold_start_items_recommendations(number_max_of_recommendations)
        
        candidate_matrix = similar_user_preferences[candidate_items].copy()
        
       #
        weighted_scores = candidate_matrix.multiply(similar_users, axis=0)
        
        # numerador usado en la fórmula de predicción 
        numerator = weighted_scores.fillna(0).sum(axis=0)

        #denominador usado en la fórmula de predicción
    
        #se calcula la puntuación de recomendación
        deviation = numerator / sum_similarity
        recommendation_scores = user_mean_rating + deviation 
        
        # Aseguramos que las puntuaciones estén dentro del rango de calificación (1 a 5)
        recommendation_scores = recommendation_scores.clip(lower=1.0, upper=5.0) 
        # Ordenamos las recomendaciones por puntuación
        recomendaciones_ordenadas = recommendation_scores.sort_values(ascending=False)
        return recomendaciones_ordenadas.head(number_max_of_recommendations).index.tolist()
        
    else:
        # Usuario nuevo sin preferencias
        return cold_start_items_recommendations(number_max_of_recommendations)
    

Ejemplo de uso de la función de recomendaciones

In [2]:
user_id = 350
recommendations = get_recommendations(user_id, 10)
print(f"Items recomendados para el usuario {user_id}: {recommendations}")

Items recomendados para el usuario 350: ['Renacimiento Cultural', 'Yoga Aéreo', 'Desarrollo de Videojuegos Unity', 'La Conquista del Espacio', 'Pilates en Casa', 'Crónicas de la Sombra', 'La Profecía del Sol', 'Escultura Moderna', 'Asesinato en el Tren Nocturno', 'Guía de Inversión Inteligente']


#### Estrategia de Evaluación del modelo
Levaremos a cabo los siguientes pasos:

1. Separar el DataFrame de preferencias en conjuntos de entrenamiento y prueba.

2. Recalcular las matrices solo con los datos de entrenamiento.

3. Definimos una función de evaluación que itere sobre el conjunto de prueba, use nuestro sistema de recomendación para generar predicciones y calcule las métricas de las mismas.

##### 1.Separación del DataFrame de preferencias en conjuntos de entrenamiento y prueba.
Para dividir el Dataframe de preferencias en train y test usamos el método holdout, que selecciona las últimas k interacciones de cada usuario para el conjunto de prueba. 
Seleccionamos este método porque es simple y efectivo para evaluar sistemas de recomendación, debido a que refleja escenarios del mundo real donde queremos predecir futuras interacciones basadas en el historial pasado. 

In [7]:
def split_dataframe(df_full, k_holdout)-> tuple:
    """Divide el DataFrame completo en conjuntos de entrenamiento y prueba utilizando el método holdout. Este método selecciona las últimas k interacciones de cada usuario para el conjunto de prueba.
    Args:
        df_full (pd.DataFrame): DataFrame completo con las interacciones de usuario-item.
        k_holdout (int): Número de interacciones por usuario a incluir en el conjunto de prueba.
    Returns:
        tuple: (train, test) donde 'train' es el conjunto de entrenamiento y 'test' es el conjunto de prueba.
    """
   #también podríamos usar sklearn.model_selection.GroupShuffleSplit para hacer el split por usuario 
    
    test = df_full.groupby('user_id').tail(k_holdout).copy()
    train = df_full.drop(test.index).copy()
    return train, test

##### 2.Recalculamos las matrices solo con los datos de entrenamiento.
Recalculamos las matrices usuario-item y de similitud solo con los datos de entrenamiento, y preparamos el conjunto de prueba. 
Esto es necesario para evaluar el sistema recomendador, ya que no podemos usar datos de prueba para generar recomendaciones.


In [6]:
def prepare_matrices_for_evaluation(df_full, k_holdout):
    """
    calcula las matrices solo con los datos de entrenamiento y prepara el conjunto de prueba.
    """
    
    # Separamos el DataFrame en conjuntos de entrenamiento y prueba usando la función definida antes
    train_df, test_set = split_dataframe(df_full, k_holdout)
    # Contrucción de la matriz usuario-item solo con los datos de entrenamiento
    matrix = train_df.pivot_table(index='user_id', columns='name', values='preference_value')
    
    # Normalizamos la matriz
    user_item_matrix = matrix.copy()
    row_mean = user_item_matrix.mean(axis=1)
    row_std = user_item_matrix.std(axis=1)
    row_std[row_std == 0] = 1 
    matrix_norm_train = user_item_matrix.sub(row_mean, axis=0).div(row_std, axis=0)
    
    # Calculamos la similitud entre usuarios en el conjunto de entrenamiento
    user_item_matrix_filled = matrix_norm_train.fillna(0)
    user_similarity_cosine = cosine_similarity(user_item_matrix_filled)
    user_ids = user_item_matrix_filled.index.tolist()
    user_similarity_train = pd.DataFrame(
        user_similarity_cosine, 
        index=user_ids, 
        columns=user_ids
    )
    user_similarity_train.index = user_similarity_train.index.astype(str)
    user_similarity_train.columns = user_similarity_train.columns.astype(str)
    
    # Preparamos el conjunto de prueba en formato adecuado
    actual_items_test = (
        test_set
        .groupby('user_id')['name'] # Usamos el nombre del ítem, no el ID
        .apply(set)
    )
    
    return matrix_norm_train, user_similarity_train, actual_items_test, train_df, row_mean

##### 3. Función de evaluación
###### Metricas
Para evaluar el sistema recomendador primero es necesario elegir una métrica de evaluación, nosotros usaremos 
* ***Precisión***: Mide la proporción de ítems que usted recomendó y que el usuario realmente consumió o quiso.
* **Recall**: Mide la proporción de ítems que el usuario de verdad quería (según el conjunto de test) y que el modelo logró incluir en la lista de recomendaciones.
* **F1-Score**: Es la forma en que se combinan la Precisión y el Recall en un solo número. Solo tendrá un F1-Score alto si tanto la Precisión como el Recall son buenos.


In [5]:
def calculate_metrics(recommended_items, actual_items,n):
    """ Calcula precision, Recall y F1 Score para un usuario dado sus items recomendados y los items reales.
    Args:
        recommended_items (list): Lista de items recomendados.
        actual_items (set): Conjunto de items reales
        n (int): numero de recomendaciones"""
    hit_items = set(recommended_items).intersection(actual_items)
    num_hits = len(hit_items)
    
    precision = num_hits / n if n > 0 else 0
    
    if len(actual_items) > 0:
        recall = num_hits / len(actual_items)
    else:
        recall = 0
        
    if (precision + recall) > 0:
        f1_score = 2 * (precision * recall) / (precision + recall)
    else:
        f1_score = 0
        
    return {
        'Precision': precision,
        'Recall': recall,
        'F1-Score': f1_score
    }

Ahora si podemos formar la funcion de evaluacion

In [4]:
def evaluate_model( n_recs=10, k_holdout=1):
  """Evalúa el sistema recomendador usando un enfoque Holdout.
  Args:
    n_recs (int): Número de recomendaciones a generar por usuario.
    k_holdout (int): Número de interacciones a reservar para el conjunto de prueba por usuario.
  """
  
  #En el programa original usabamos variables globales, ya que usamos siempre los mismos datos, aqui debemos reasignarlas localmente para la evaluación
  # Las variables globales se reasignan localmente para la prueba
  global MATRIX_NORM, USER_SIMILARITY, DF
  # Guardamos una copia de las matrices originales
  original_matrix_norm = MATRIX_NORM
  original_user_similarity = USER_SIMILARITY
  original_df = DF
  
  # Preparamos las matrices de entrenamiento y el set de prueba
  MATRIX_NORM, USER_SIMILARITY, actual_items_test, DF, ROW_MEAN_TRAIN = prepare_matrices_for_evaluation(original_df, k_holdout)

  evaluation_results = []
  
  for user_id, actual_set in actual_items_test.items():
    # Verificamos que el usuario pueda ser evaluado (tiene ítems en el test set)
    if len(actual_set) == 0:
      continue  
    # Ahora que sabemos que el usuario puede ser evaluado
    # Generamos recomendaciones usando las matrices de entrenamiento
    recommended_item_names = get_recommendations(user_id, n_recs)
    
    # Calculamos las metricas
    metrics = calculate_metrics(recommended_item_names, actual_set,n_recs)
    metrics['user_id'] = user_id
    evaluation_results.append(metrics)
    
  # Restablecemos las matrices originales
  MATRIX_NORM = original_matrix_norm
  USER_SIMILARITY = original_user_similarity
  DF = original_df
  
  # Resultado de la evaluación
  results_df = pd.DataFrame(evaluation_results)
  
  return {
          'Precision': float(results_df['Precision'].mean()),
          'Recall': float(results_df['Recall'].mean()),
          'F1-Score': float(results_df['F1-Score'].mean())}

#### Evaluación del modelo

##### Prueba A
Planteamos un escenario similar al establecido por defecto en la especificado en la documentacion de la API y un holdout moderado.
Oculta dos interacciones recientes.
* n=5
* k=2

In [12]:
import time
tiempo_inicial = time.time()
metricas_prueba_a_modelo_1 = evaluate_model(5, 2)
tiempo_prueba_a_modelo_1 = time.time() - tiempo_inicial
print(f"Metricas del modelo evaluado: {metricas_prueba_a_modelo_1}")
print(f"Tiempo de evaluación del modelo: {tiempo_prueba_a_modelo_1} segundos")

Metricas del modelo evaluado: {'Precision': 0.04371428571428572, 'Recall': 0.10928571428571429, 'F1-Score': 0.06244897959183675}
Tiempo de evaluación del modelo: 10.824275016784668 segundos


##### Prueba B
Esta prueba se enfoca en asegurar que las primeras recomendaciones que ve el usuario son dealta calidad, utilizando una lista muy corta.
* n=3
* k=4


In [10]:
tiempo_inicial = time.time()
metricas_prueba_b_modelo_1 = evaluate_model(3, 4)
tiempo_prueba_b_modelo_1 = time.time() - tiempo_inicial
print(f"Metricas del modelo evaluado: {metricas_prueba_b_modelo_1}")
print(f"Tiempo de evaluación del modelo: {tiempo_prueba_b_modelo_1} segundos")

Metricas del modelo evaluado: {'Precision': 0.06809523809523808, 'Recall': 0.05107142857142857, 'F1-Score': 0.058367346938775516}
Tiempo de evaluación del modelo: 10.674531698226929 segundos


##### Prueba C
Esta prueba mide el potencial máximo de su modelo para encontrar ítems relevantes.
Utilizamos un N mucho mayor que K
* n=15
* k=3

In [26]:
tiempo_inicial = time.time()
metricas_prueba_c_modelo_1 = evaluate_model(15, 3)
tiempo_prueba_c_modelo_1 = time.time() - tiempo_inicial
print(f"Metricas del modelo evaluado: {metricas_prueba_c_modelo_1}")
print(f"Tiempo de evaluación del modelo: {tiempo_prueba_c_modelo_1} segundos")

Metricas del modelo evaluado: {'Precision': 0.06114285714285714, 'Recall': 0.3057142857142857, 'F1-Score': 0.10190476190476191}
Tiempo de evaluación del modelo: 7.593007564544678 segundos


## Modelo filtro colaborativo basado en items.
Utilizaremos la similitud entre ítems en función de los ratings que han recibido. Nuestra hipótesis es que los ítems similares a los que un usuario ya ranqueó alto, tambien le gustaran.

Los pasos a seguir son los siguientes:
1. Encontrar Ítems Similares: Calcular la similitud entre cada par de ítems, basándose en los ratings que han recibido de todos los usuarios.
2. Identificar Ítems Candidatos: Para el usuario objetivo, identificar los ítems que no ha consumido o calificado.
3. Calcular la Predicción: Para cada ítem candidato, predecir su rating utilizando una suma ponderada de las calificaciones que el usuario ya dio a los ítems similares.
4. Recomendar items en función de este ranking.

### Construcción del modelo
#### Matriz de preferencias
Vamos a crear un amatriz Usuario x Item con el puntaje dado por cada usuario a cada item que compro. Es una matriz dispersa por la que habrá muchos valores nulos.

In [13]:
matrix = df.pivot_table(index='user_id', columns='name', values='preference_value')# Creamos la matriz usuario-item
matrix.head()

NameError: name 'df' is not defined

normalizamos la matriz

In [45]:
user_item_matrix = matrix.copy()# copia para trabajar sin alterar la original
row_mean_model_2 = user_item_matrix.mean(axis=1)# Promedio por fila (media de usuario)
row_std = user_item_matrix.std(axis=1)# Desviación estándar por fila
row_std[row_std == 0] = 1 # Evitamos división por cero
matrix_norm = user_item_matrix.sub(row_mean_model_2, axis=0).div(row_std, axis=0)# Normalizamos por usuario
matrix_norm.head()

name,Agujeros Negros,Algoritmos Avanzados en Java,Aromaterapia,Asesinato en el Tren Nocturno,Atlas Mundial Actualizado,Bases de Datos SQL,Biografía de Marie Curie,Bolsa de Valores Avanzada,Caligrafía Japonesa,Cartas de Amor Perdidas,...,Sin Rastro,Sonetos al Mar,Sueños de Androides,Tapas Españolas,Testigo Ocular,Versos Olvidados,Voces de la Guerra Civil,Yoga Aéreo,Yoga para Principiantes,Época Medieval
user_id,,,,,,,,,,,,,,,,,,,,,
1,NaN,NaN,NaN,NaN,NaN,NaN,-1.106797,NaN,NaN,NaN,...,0.474342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,0.380319,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,-0.253546,NaN,NaN,1.014185,NaN,NaN,1.014185,NaN
3,NaN,NaN,NaN,NaN,-0.283193,NaN,NaN,NaN,-1.227168,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,1.587011,-0.083527,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,-0.918796,NaN,NaN,0.751742,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.490788


### Similitud entre ítems
Calculamos la similitud entre ítems.
Usaremos la similitud de coseno para determinar la similitud entre usuarios. 


Transponemos la matriz normalizada porque ahora queremos similitud entre ítems

In [46]:
item_item_matrix_filled = matrix_norm.fillna(0).T 

In [47]:
from sklearn.metrics.pairwise import cosine_similarity
item_similarity_cosine = cosine_similarity(item_item_matrix_filled) # Calculamos similitud entre ítems
item_names = item_item_matrix_filled.index.tolist()# Nombres de los ítems
item_similarity = pd.DataFrame( # Creamos la matriz de similitud de ítems
    item_similarity_cosine, 
    index=item_names, 
    columns=item_names
)
item_similarity.index = item_similarity.index.astype(str)
item_similarity.columns = item_similarity.columns.astype(str)
item_similarity.head()

,Agujeros Negros,Algoritmos Avanzados en Java,Aromaterapia,Asesinato en el Tren Nocturno,Atlas Mundial Actualizado,Bases de Datos SQL,Biografía de Marie Curie,Bolsa de Valores Avanzada,Caligrafía Japonesa,Cartas de Amor Perdidas,...,Sin Rastro,Sonetos al Mar,Sueños de Androides,Tapas Españolas,Testigo Ocular,Versos Olvidados,Voces de la Guerra Civil,Yoga Aéreo,Yoga para Principiantes,Época Medieval
Agujeros Negros,1.0,0.000000,0.000000,0.0,0.000000,0.606982,0.000000,0.0,-0.032397,-0.338851,...,0.000000,0.0,0.000000,0.000000,0.000000,0.000000,0.357517,0.000000,0.000000,0.0
Algoritmos Avanzados en Java,0.0,1.000000,-0.097384,0.0,-0.048788,0.000000,0.000000,0.0,0.000000,0.000000,...,0.000000,0.0,0.000000,0.000000,-0.347557,0.000000,0.000000,0.514529,0.000000,0.0
Aromaterapia,0.0,-0.097384,1.000000,0.0,0.000000,0.000000,0.000000,0.0,-0.199938,0.000000,...,-0.101397,0.0,-0.125417,0.199172,0.065767,0.000000,0.024810,-0.226955,0.000000,0.0
Asesinato en el Tren Nocturno,0.0,0.000000,0.000000,1.0,0.000000,0.000000,0.166835,0.0,0.000000,0.000000,...,0.000000,0.0,0.070108,0.000000,0.000000,0.168935,-0.469667,0.000000,0.051531,0.0
Atlas Mundial Actualizado,0.0,-0.048788,0.000000,0.0,1.000000,0.000000,0.000000,0.0,0.141094,0.319473,...,0.000000,0.0,-0.256885,0.000000,0.000000,0.000000,0.000000,-0.023645,0.000000,0.0


Dado un usuario

In [48]:
user = "350"

Ítems calificados por el usuario

In [49]:
user_mean_rating = df [df ['user_id'] == user]['preference_value'].mean()# Calculamos la media de calificaciones del usuario
user_ratings_norm = matrix_norm.loc[int(user)].dropna()# Obtenemos las calificaciones normalizadas del usuario
items_rated_by_user = user_ratings_norm.index.tolist()# Ítems calificados por el usuario
items_rated_by_user

['Desarrollo Web con React',
 'El Legado de Einstein',
 'Fotografía Digital',
 'Geología Terrestre',
 'Masajes Terapéuticos',
 'Mitología Griega',
 'Robots en el Tiempo']

Filtramos ítems no calificados y obtenemos los Items candidatos

In [50]:
# Filtramos ítems no calificados
top_unrated_globally = df [~df['name'].isin(items_rated_by_user)] \
    .groupby('name')['preference_value'].count() \
    .sort_values(ascending=False).head(300).index.tolist() # Limitar a 300 candidatos
# Items candidatos
candidate_items = list(set(top_unrated_globally))
candidate_items

['Egipto Faraónico',
 'Manual de Liderazgo Ágil',
 'Data Science con R',
 'Agujeros Negros',
 'Mapas Antiguos',
 'Bases de Datos SQL',
 'Versos Olvidados',
 'Renacimiento Cultural',
 'El Silencio del Testigo',
 'El Eco de las Palabras',
 'Escultura Moderna',
 'Ciberseguridad Esencial',
 'Cocina Tailandesa',
 'Negociación y Persuasión',
 'Cócteles Clásicos',
 'Atlas Mundial Actualizado',
 'Dieta Keto',
 'El Universo en Expansión',
 'Desarrollo de Videojuegos Unity',
 'Crimen en la Mansión',
 'Época Medieval',
 'Guerras Mundiales',
 'Estrategias de Venta',
 'Sin Rastro',
 'Finanzas Personales 2026',
 'Cloud Computing AWS',
 'Repostería Francesa',
 'El Caso del Collar Perdido',
 'Machine Learning Básico',
 'Culturas Indígenas de América',
 'Pilates en Casa',
 'Poemas del Infinito',
 'Yoga Aéreo',
 'Bolsa de Valores Avanzada',
 'Redes Neuronales',
 'Biografía de Marie Curie',
 'La Vida en Marte',
 'Sonetos al Mar',
 'Crónicas de la Sombra',
 'Recetas de la Abuela',
 'Nutrición Deportiva',


Calculamos la puntuación para cada ítem candidato,c onsideramos solo los 10 vecinos más similares

In [51]:
K_NEIGHBORS=10# Número de vecinos más similares a considerar
recommendation_scores = {}
for candidate_item in candidate_items:# Calculamos la puntuación para cada ítem candidato
    
    if candidate_item not in item_similarity.index:
        continue
    item_similarity_vector = item_similarity.loc[candidate_item]
    
    rated_items_similarity = item_similarity_vector[items_rated_by_user]
    final_ratings = user_ratings_norm[items_rated_by_user]

    if K_NEIGHBORS> 0:# Consideramos solo los K vecinos más similares
        neighbor_data = pd.DataFrame({
            'similarity': rated_items_similarity,
            'rating': final_ratings
        }).dropna()
        # Ordenamos por similitud absoluta y seleccionamos los top K
        top_neighbors = neighbor_data['similarity'].abs().sort_values(ascending=False).head(K_NEIGHBORS).index
        # Obtenemos los valores finales para los top vecinos
        final_similarity = rated_items_similarity[top_neighbors]
        # Obtener las calificaciones correspondientes
        final_ratings = final_ratings[top_neighbors]
    
    numerator = (final_similarity * final_ratings).sum()# Calculamos el numerador de la fórmula de predicción
    denominator = final_similarity.abs().sum() # Calculamos el denominador de la fórmula de predicción
    
    if denominator > 0: # Evitamos división por cero
        deviation = numerator / denominator
        prediction = user_mean_rating + deviation
        recommendation_scores[candidate_item] = prediction
recommendation_scores
        

{'Egipto Faraónico': np.float64(nan),
 'Manual de Liderazgo Ágil': np.float64(nan),
 'Data Science con R': np.float64(nan),
 'Mapas Antiguos': np.float64(nan),
 'Bases de Datos SQL': np.float64(nan),
 'Versos Olvidados': np.float64(nan),
 'Renacimiento Cultural': np.float64(nan),
 'El Silencio del Testigo': np.float64(nan),
 'El Eco de las Palabras': np.float64(nan),
 'Escultura Moderna': np.float64(nan),
 'Ciberseguridad Esencial': np.float64(nan),
 'Cocina Tailandesa': np.float64(nan),
 'Negociación y Persuasión': np.float64(nan),
 'Cócteles Clásicos': np.float64(nan),
 'Atlas Mundial Actualizado': np.float64(nan),
 'Dieta Keto': np.float64(nan),
 'El Universo en Expansión': np.float64(nan),
 'Desarrollo de Videojuegos Unity': np.float64(nan),
 'Crimen en la Mansión': np.float64(nan),
 'Época Medieval': np.float64(nan),
 'Guerras Mundiales': np.float64(nan),
 'Estrategias de Venta': np.float64(nan),
 'Sin Rastro': np.float64(nan),
 'Finanzas Personales 2026': np.float64(nan),
 'Cloud

Convertimos a valores valios y ordenamos las recomendaciones por puntuación en orden descendente

In [52]:
recommendation_scores_series = pd.Series(recommendation_scores)# Convertimos a Serie para facilitar el manejo
recommendation_scores_series = recommendation_scores_series.clip(lower=1.0, upper=5.0) # Aseguramos que las puntuaciones estén dentro del rango válido
recomendaciones_ordenadas = recommendation_scores_series.sort_values(ascending=False)# Ordenamos las recomendaciones por puntuación en orden descendente

#### Recomendaciones
Recomendados los 10 ítems con puntuación más alta

In [53]:

number_max_of_recommendations = 10# Número máximo de recomendaciones a retornar
print(f"Items recomendados para el usuario {user}: ")
recomendaciones_ordenadas.head(number_max_of_recommendations).index.tolist()# Retornamos los nombres de los ítems recomendados

Items recomendados para el usuario 350: 


['Egipto Faraónico',
 'Manual de Liderazgo Ágil',
 'Data Science con R',
 'Mapas Antiguos',
 'Bases de Datos SQL',
 'Versos Olvidados',
 'Renacimiento Cultural',
 'El Silencio del Testigo',
 'El Eco de las Palabras',
 'Escultura Moderna']

### Evaluacion del modelo
Primero encapsulamos el sistema en funciones para simplicidad

In [14]:

K_NEIGHBORS_model_2 = 50 # Número de vecinos para el modelo 2 
# Declaración de variables globales 
DF_MODEL_2  = None # DataFrame de preferencias
MATRIX_NORM_MODEL_2 = None # Matriz normalizada
ITEM_SIMILARITY = None #Ahora usamos similitud entre ítems
USERS_DF_MODEL_2 = None # DataFrame de usuarios
ITEMS_DF_MODEL_2 = None # DataFrame de items
row_mean_model_2 = None # Promedio por fila (media de usuario)
# ------------------------------------------------------------------------------------------------------------------

# Función para cargar y preparar los datos para el modelo 2
#A demás de los cambios en la similitud, este modelo usa la desviación estándar para normalizar
def initial_load_model_2():
    """Carga los datos de SQLite y genera las matrices necesarias para el sistema recomendador IBCF.
    Returns:
        tuple: (df, matrix_norm, item_similarity, users_df, items_df, row_mean_model_2)"""
    if not(os.path.exists(DB_NAME)): # Verificamos si la base de datos ya existe
        print(f"Base de datos '{DB_NAME}' no encontrada. Creandola e inicializándola...")
        initialize_db() #Inicializa la DB si no existe con la función definida antes
    
    # Consulta SQL para unir items y preferences
    SQL_QUERY = """
SELECT 
    T1.id as item_id,
    T1.name,
    T2.user_id,
    T2.preference_value
FROM 
    items AS T1 
INNER JOIN 
    preferences AS T2
ON 
    T1.id = T2.item_id;
"""  
    conn = sqlite3.connect(DB_NAME)# Abrimos la conexión a la base de datos
    df = pd.read_sql_query(SQL_QUERY, conn)# Leemos las preferencias uniendo items y preferences
    users_df = pd.read_sql_query("SELECT * FROM users", conn)# Leemos los usuarios desde la base de datos
    items_df = pd.read_sql_query("SELECT * FROM items", conn)# Leemos los items desde la base de datos
    conn.close()# Cerramos la conexión a la base de datos
    #Procesamos los datos como se hizo anteriormente
    df.dropna(inplace=True)# Eliminamos filas con valores nulos
    df.drop_duplicates(subset=['item_id', 'user_id'], inplace=True) # Eliminamos filas duplicadas
    valid_user_ids = set(users_df['id'])# Obtenemos los IDs de usuarios válidos
    valid_item_ids = set(items_df['id'])# Obtenemos los IDs de items válidos
    df = df[df['user_id'].isin(valid_user_ids) & df['item_id'].isin(valid_item_ids)]# Filtramos el DataFrame (identificamos referencias inválidas)
    df = df[(df['preference_value'] >= 1) & (df['preference_value'] <= 5)]# Filtramos el DataFrame (eliminamos valores fuera de rango)
    df['item_id'] = df['item_id'].astype(int)# Convertimos la columna 'item_id' a tipo entero
    df['name'] = df['name'].astype(str)# Convertimos la columna 'name' a tipo cadena de texto
    df['user_id'] = df['user_id'].astype(int)# Convertimos la columna 'user_id' a tipo entero
    df['preference_value'] = df['preference_value'].astype(int)# Convertimos la columna 'preference_value' a tipo entero
    users_df.dropna(subset=['id'], inplace=True)# Eliminamos filas con valores nulos en las columnas 'id' 
    users_df.dropna(subset=['username'], inplace=True)# Eliminamos filas con valores nulos en la columna 'username'
    users_df.drop_duplicates(subset=['id'], inplace=True)# Eliminamos usuarios duplicados según la columna 'id'
    users_df.drop_duplicates(subset=['username'], inplace=True)# Eliminamos usuarios duplicados según la columna 'username'
    users_df['id'] = users_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
    users_df['username'] = users_df['username'].astype(str)
    users_df['telephone'] = users_df['telephone'].astype(str)# Aseguramos que la columna 'telephone' sea de tipo string
    users_df['birthdate'] = pd.to_datetime(users_df['birthdate'])# Convertimos la columna 'birthdate' a tipo datetime
    users_df['gender'] = users_df['gender'].astype(str)# seguramos que la columna 'gender' sea de tipo string
    users_df['created_at'] = pd.to_datetime(users_df['created_at'])# Convertimos la columna 'created_at' a tipo datetime
    items_df['id'].dropna(inplace=True)# Eliminamos filas con valores nulos en la columna 'id'
    items_df['id'] = items_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
    items_df['name'] = items_df['name'].astype(str)# Aseguramos que la columna 'name' sea de tipo string
    items_df['price'] = items_df['price'].astype(float)# Aseguramos que la columna 'price' sea de tipo float
    items_df['category'] = items_df['category'].astype(str)# Aseguramos que la columna 'category' sea de tipo string
    items_df['description'] = items_df['description'].astype(str)# Aseguramos que la columna 'description0' sea de tipo string
    # Creamos las matrices necesarias para el sistema recomendador
    matrix = df.pivot_table(index='user_id', columns='name', values='preference_value')# Matriz usuario-item
    user_item_matrix = matrix.copy()# copia para trabajar sin alterar la original
    row_mean_model_2 = user_item_matrix.mean(axis=1)# Promedio por fila (media de usuario)
    row_std = user_item_matrix.std(axis=1)# Desviación estándar por fila
    row_std[row_std == 0] = 1 # Evitamos división por cero
    matrix_norm = user_item_matrix.sub(row_mean_model_2, axis=0).div(row_std, axis=0)# Normalizamos por usuario
    # Calculamos la similitud entre ítems
    item_item_matrix_filled = matrix_norm.fillna(0).T # Transponemos la matriz normalizada
    item_similarity_cosine = cosine_similarity(item_item_matrix_filled) # Calculamos similitud entre ítems
    item_names = item_item_matrix_filled.index.tolist()# Nombres de los ítems
    item_similarity = pd.DataFrame( # Creamos la matriz de similitud de ítems
        item_similarity_cosine, 
        index=item_names, 
        columns=item_names
    )
    item_similarity.index = item_similarity.index.astype(str)
    item_similarity.columns = item_similarity.columns.astype(str)
    # -----------------------------------------------------

    # Retornamos los datos procesados (USER_SIMILARITY reemplazado por ITEM_SIMILARITY)
    return df, matrix_norm, item_similarity, users_df, items_df,row_mean_model_2

try:
    
    DF_MODEL_2 , MATRIX_NORM_MODEL_2, ITEM_SIMILARITY, USERS_DF_MODEL_2, ITEMS_DF_MODEL_2, row_mean_model_2 = initial_load_model_2()
except Exception as e:
    print(f" ERROR FATAL: La aplicación no pudo iniciar debido al error de carga/procesamiento: {e}")

# Función de recomendación para el modelo 2
def get_recommendations_model_2(user_id: int, number_max_of_recommendations: int) -> list:
    """Genera recomendaciones de ítems para un usuario específico utilizando filtrado basado en ítems
    Args:
        user_id (int): ID del usuario para el cual se generan recomendaciones.
        number_max_of_recommendations (int): Número máximo de items a recomendar.
    Returns:
        list: Lista de nombres de items recomendados.
    """
    if user_has_preferences(user_id):
        user_mean_rating = DF_MODEL_2 [DF_MODEL_2 ['user_id'] == user_id]['preference_value'].mean()
        if pd.isna(user_mean_rating):
             user_mean_rating = 3.0 

        user_ratings_norm = MATRIX_NORM_MODEL_2.loc[user_id].dropna()
        items_rated_by_user = user_ratings_norm.index.tolist()
        
        # Obtenemos los K ítems más populares no calificados
        top_unrated_globally = DF_MODEL_2 [~DF_MODEL_2 ['name'].isin(items_rated_by_user)] \
            .groupby('name')['preference_value'].count() \
            .sort_values(ascending=False).head(300).index.tolist() # Limitar a 300 candidatos
        # Items candidatos
        candidate_items = list(set(top_unrated_globally))
        
        if not candidate_items:# Si no hay ítems candidatos, usamos el cold-start
            return cold_start_items_recommendations(number_max_of_recommendations)

       
        
        recommendation_scores = {}
        for candidate_item in candidate_items:# Calculamos la puntuación para cada ítem candidato
            
            if candidate_item not in ITEM_SIMILARITY.index:
                continue
            item_similarity_vector = ITEM_SIMILARITY.loc[candidate_item]
            
            rated_items_similarity = item_similarity_vector[items_rated_by_user]
            final_ratings = user_ratings_norm[items_rated_by_user]
            
            if K_NEIGHBORS_model_2 > 0:# Consideramos solo los K vecinos más similares
                neighbor_data = pd.DataFrame({
                    'similarity': rated_items_similarity,
                    'rating': final_ratings
                }).dropna()
                # Ordenamos por similitud absoluta y seleccionamos los top K
                top_neighbors = neighbor_data['similarity'].abs().sort_values(ascending=False).head(K_NEIGHBORS_model_2).index
                # Obtenemos los valores finales para los top vecinos
                final_similarity = rated_items_similarity[top_neighbors]
                # Obtener las calificaciones correspondientes
                final_ratings = final_ratings[top_neighbors]
            
            numerator = (final_similarity * final_ratings).sum()# Calculamos el numerador de la fórmula de predicción
            denominator = final_similarity.abs().sum() # Calculamos el denominador de la fórmula de predicción
            
            if denominator > 0: # Evitamos división por cero
                deviation = numerator / denominator
                prediction = user_mean_rating + deviation
                recommendation_scores[candidate_item] = prediction
                
        
        recommendation_scores_series = pd.Series(recommendation_scores)# Convertimos a Serie para facilitar el manejo
        
        if recommendation_scores_series.empty:# Si no hay puntuaciones calculadas, usamos el cold-start
            return cold_start_items_recommendations(number_max_of_recommendations)
            
        recommendation_scores_series = recommendation_scores_series.clip(lower=1.0, upper=5.0) # Aseguramos que las puntuaciones estén dentro del rango válido

        recomendaciones_ordenadas = recommendation_scores_series.sort_values(ascending=False)# Ordenamos las recomendaciones por puntuación en orden descendente
        return recomendaciones_ordenadas.head(number_max_of_recommendations).index.tolist()# Retornamos los nombres de los ítems recomendados
        
    else:# Usuario nuevo sin preferencias
        return cold_start_items_recommendations(number_max_of_recommendations)#usamos el cold-start


#### Estrategia de Evaluación del modelo
Usaremos la misma estrategia antes,
Levaremos a cabo los siguientes pasos:

1. Separar el DataFrame de preferencias en conjuntos de entrenamiento y prueba.

2. Recalcular las matrices solo con los datos de entrenamiento.

3. Definimos una función de evaluación que itere sobre el conjunto de prueba, use nuestro sistema de recomendación para generar predicciones y calcule las métricas de las mismas.

##### 1.Separación del DataFrame de preferencias en conjuntos de entrenamiento y prueba.
usamos la misma funcion que antes.

##### 2.Recalculamos las matrices solo con los datos de entrenamiento.


In [15]:
def prepare_matrices_for_evaluation_model_2(df_full, k_holdout):
    """
    Calcula las matrices de entrenamiento para el modelo 2 y prepara el conjunto de prueba.
    Args:
        df_full (pd.DataFrame): DataFrame completo con las interacciones de usuario-item.
        k_holdout (int): Número de interacciones por usuario a incluir en el conjunto de prueba.

    """
    #usamos la función split_dataframe definida antes
    train_df, test_set = split_dataframe(df_full, k_holdout)
    matrix = train_df.pivot_table(index='user_id', columns='name', values='preference_value')
    
    # Normalizamos la matriz
    user_item_matrix = matrix.copy()
    row_mean_model_2 = user_item_matrix.mean(axis=1)
    row_std = user_item_matrix.std(axis=1)
    row_std[row_std == 0] = 1 
    matrix_norm_train = user_item_matrix.sub(row_mean_model_2, axis=0).div(row_std, axis=0)
    
    # Calculamos la similitud entre ítems en el conjunto de entrenamiento
    item_item_matrix_filled_train = matrix_norm_train.fillna(0).T
    item_similarity_cosine_train = cosine_similarity(item_item_matrix_filled_train)
    item_names_train = item_item_matrix_filled_train.index.tolist()
    item_similarity_train = pd.DataFrame(
        item_similarity_cosine_train, 
        index=item_names_train, 
        columns=item_names_train
    )
    item_similarity_train.index = item_similarity_train.index.astype(str)
    item_similarity_train.columns = item_similarity_train.columns.astype(str)
    
    actual_items_test = (
        test_set
        .groupby('user_id')['name']
        .apply(set)
    )
    
    # Retorna item_similarity_train
    return matrix_norm_train, item_similarity_train, actual_items_test, train_df, row_mean_model_2,


##### 3. Función de evaluación
###### Metricas
Usamos las mismas metricas que con el modelo anterior, para que la comparacion se justa

In [16]:
def evaluate_model_2( n_recs=10, k_holdout=1):
    """Evalúa el modelo 2 del sistema recomendador usando un enfoque Holdout.
    Args:
        n_recs (int): Número de recomendaciones a generar por usuario.
        k_holdout (int): Número de interacciones a reservar para el conjunto de prueba por usuario.
    """
    
    # Las variables globales se reasignan localmente para la prueba
    global MATRIX_NORM_MODEL_2, ITEM_SIMILARITY, DF_MODEL_2  
    # Guardamos una copia de las matrices originales
    original_matrix_norm = MATRIX_NORM_MODEL_2
    original_item_similarity = ITEM_SIMILARITY 
    original_df = DF_MODEL_2 
    
    # Preparamos las matrices de entrenamiento y el set de prueba
    MATRIX_NORM_MODEL_2, ITEM_SIMILARITY, actual_items_test, DF_MODEL_2 , ROW_MEAN_TRAIN = prepare_matrices_for_evaluation_model_2(original_df, k_holdout)

    evaluation_results = []
    
    for user_id, actual_set in actual_items_test.items():
        if len(actual_set) == 0:
            continue  
        
        # Generamos recomendaciones usando las matrices de entrenamiento
        recommended_item_names = get_recommendations_model_2(user_id, n_recs)
        
        # Calculamos las metricas usando la función definida antes
        metrics = calculate_metrics(recommended_item_names, actual_set,n_recs)
        metrics['user_id'] = user_id
        evaluation_results.append(metrics)
        
    # Restablecemos las matrices originales
    MATRIX_NORM_MODEL_2 = original_matrix_norm
    ITEM_SIMILARITY = original_item_similarity 
    DF_MODEL_2  = original_df
    
    # Resultado de la evaluación
    results_df = pd.DataFrame(evaluation_results)
    
    return {
        'Precision': float(results_df['Precision'].mean()),
        'Recall': float(results_df['Recall'].mean()),
        'F1-Score': float(results_df['F1-Score'].mean())}

#### Evaluación del modelo

##### Prueba A
Planteamos un escenario similar al establecido por defecto en la especificado en la documentacion de la API y un holdout moderado.
Oculta dos interacciones recientes.
* n=5
* k=2

In [17]:
tiempo_inicial = time.time()
metricas_prueba_a_modelo_2 = evaluate_model_2(5, 2)
tiempo_prueba_a_modelo_2 = time.time() - tiempo_inicial
print(f"Metricas del modelo evaluado: {metricas_prueba_a_modelo_2}")
print(f"Tiempo de evaluación del modelo: {tiempo_prueba_a_modelo_2} segundos")

Metricas del modelo evaluado: {'Precision': 0.021714285714285714, 'Recall': 0.054285714285714284, 'F1-Score': 0.031020408163265307}
Tiempo de evaluación del modelo: 480.45237588882446 segundos


##### Prueba B
Esta prueba se enfoca en asegurar que las primeras recomendaciones que ve el usuario son dealta calidad, utilizando una lista muy corta.
* n=3
* k=4

In [18]:
tiempo_inicial = time.time()
metricas_prueba_b_modelo_2 = evaluate_model_2(3, 4)
tiempo_prueba_b_modelo_2 = time.time() - tiempo_inicial
print(f"Metricas del modelo evaluado: {metricas_prueba_b_modelo_2}")
print(f"Tiempo de evaluación del modelo: {tiempo_prueba_b_modelo_2} segundos")

Metricas del modelo evaluado: {'Precision': 0.0519047619047619, 'Recall': 0.03892857142857143, 'F1-Score': 0.04448979591836735}
Tiempo de evaluación del modelo: 300.31614112854004 segundos


##### Prueba C
Esta prueba mide el potencial máximo de su modelo para encontrar ítems relevantes.
Utilizamos un N mucho mayor que K
* n=15
* k=3

In [19]:
tiempo_inicial = time.time()
metricas_prueba_c_modelo_2 = evaluate_model_2(15, 3)
tiempo_prueba_c_modelo_2 = time.time() - tiempo_inicial
print(f"Metricas del modelo evaluado: {metricas_prueba_c_modelo_2}")
print(f"Tiempo de evaluación del modelo: {tiempo_prueba_c_modelo_2} segundos")

Metricas del modelo evaluado: {'Precision': 0.05742857142857142, 'Recall': 0.28714285714285714, 'F1-Score': 0.09571428571428571}
Tiempo de evaluación del modelo: 286.47529101371765 segundos


## Comparacion de los modelos

### Prueba A
* n=5
* k=2

In [20]:
comparison_df = pd.DataFrame({
    'Modelo 1': {**metricas_prueba_a_modelo_1, 'Tiempo (s)': tiempo_prueba_a_modelo_1},
    'Modelo 2': {**metricas_prueba_a_modelo_2, 'Tiempo (s)': tiempo_prueba_a_modelo_2},
}).T
print("\nComparativa de resultados entre Modelos para la Prueba A:")
comparison_df



Comparativa de resultados entre Modelos para la Prueba A:


,Precision,Recall,F1-Score,Tiempo (s)
Modelo 1,0.043714,0.109286,0.062449,10.824275
Modelo 2,0.021714,0.054286,0.031020,480.452376


El modelo 1 hizo mas rapido la prueba y obtuvo mejores resultados las métricas de evaluación.

### Prueba B
* n=3
* k=4

In [21]:
comparison_df = pd.DataFrame({
    'Modelo 1': {**metricas_prueba_b_modelo_1, 'Tiempo (s)': tiempo_prueba_b_modelo_1},
    'Modelo 2': {**metricas_prueba_b_modelo_2, 'Tiempo (s)': tiempo_prueba_b_modelo_2},
}).T
print("\nComparativa de resultados entre Modelos para la Prueba B:")
comparison_df


Comparativa de resultados entre Modelos para la Prueba B:


,Precision,Recall,F1-Score,Tiempo (s)
Modelo 1,0.068095,0.051071,0.058367,10.674532
Modelo 2,0.051905,0.038929,0.044490,300.316141


El modelo 1 hizo mas rapido la prueba y obtuvo mejores resultados las métricas de evaluación.

### Prueba C
* n=15
* k=3

In [22]:
comparison_df = pd.DataFrame({
    'Modelo 1': {**metricas_prueba_c_modelo_1, 'Tiempo (s)': tiempo_prueba_c_modelo_1},
    'Modelo 2': {**metricas_prueba_c_modelo_2, 'Tiempo (s)': tiempo_prueba_c_modelo_2},
}).T
print("\nComparativa de resultados entre Modelos para la Prueba B:")
comparison_df


Comparativa de resultados entre Modelos para la Prueba B:


,Precision,Recall,F1-Score,Tiempo (s)
Modelo 1,0.061143,0.305714,0.101905,16.517896
Modelo 2,0.057429,0.287143,0.095714,286.475291


El modelo 1 hizo mas rapido la prueba y obtuvo mejores resultados las métricas de evaluación.

### Tiempo promedio de procesamiento
Comparamos tiempos de generación de recomendaciones para ambos modelos para obtener una idea de su rendimiento

Medimos el tiempo de generación de recomendaciones para 500 usuarios en el Modelo 1 con 10 recomendaciones cada uno

In [28]:
tiempo_inicial = time.time()
for user in range(1, 501):
    recommendations_model_1 = get_recommendations(user, 10)
tiempo_total_modelo_1 = (time.time() - tiempo_inicial)
tiempo_promedio_modelo_1 = tiempo_total_modelo_1 / 500
print(f"\nTiempo total promedio para generar recomendaciones para 500 usuarios en el Modelo 1: {tiempo_promedio_modelo_1:.4f} segundos")


Tiempo total promedio para generar recomendaciones para 500 usuarios en el Modelo 1: 0.0122 segundos


Medimos el tiempo de generación de recomendaciones para 500 usuarios en el Modelo 2 con 10 recomendaciones cada uno

In [ ]:
tiempo_inicial = time.time()
for user in range(1, 501):
    recommendations_model_2 = get_recommendations_model_2(user, 10)
tiempo_total_modelo_2 = time.time() - tiempo_inicial
tiempo_promedio_modelo_2= tiempo_total_modelo_2 / 500
print(f"\nTiempo total para generar recomendaciones para 500 usuarios en el Modelo 2: {tiempo_promedio_modelo_2:.4f} segundos")

calculamos el porcentaje de diferencia en tiempo promedio

In [ ]:
porcentaje_diferencia_tiempo = ((tiempo_promedio_modelo_2 - tiempo_promedio_modelo_1) / tiempo_promedio_modelo_1) * 100
print(f"Porcentaje de diferencia en tiempo promedio entre Modelo 2 y Modelo 1: {porcentaje_diferencia_tiempo:.2f}%")

El modelo 2 demora casi 49 veces más que el modelo 1 en promedio por consulta para n=10, lo que lo hace inviable

### Conclusion
En la todos los casos el modelo de filtro colaborativo basado en usuarios tiene mejor rendimiento con respecto a las metricas y es muchisimo mas rapido que el modelo 2, por lo que es la mejor opcion para la implementación

# **5.Evaluación**
En la fase anterior concluimos que el modelo 1 es más rápido en promedio que el modelo 2 para generar recomendaciones, tiene mejores métricas en las pruebas realizadas y decidimos quedarnos con el modelo 1 para la aplicación final.
Antes de comprobar que se hayan cumplido los criterios de exito, calculemos el promedio general de las métricas del modelo 1 en las tres pruebas realizadas.
Calculamos el promedio en general de las métricas del modelo 1 en las tres pruebas realizadas para tener una idea general de su desempeño.

In [24]:
precision_promedio = (metricas_prueba_a_modelo_1['Precision'] + metricas_prueba_b_modelo_1['Precision'] + metricas_prueba_c_modelo_1['Precision']) / 3
recall_promedio = (metricas_prueba_a_modelo_1['Recall'] + metricas_prueba_b_modelo_1['Recall'] + metricas_prueba_c_modelo_1['Recall']) / 3
f1_score_promedio = (metricas_prueba_a_modelo_1['F1-Score'] + metricas_prueba_b_modelo_1['F1-Score'] + metricas_prueba_c_modelo_1['F1-Score']) / 3
print(f"\nPromedio general de métricas del Modelo 1 (Expresado en porcentaje):")
print(f"Precisión Promedio: {precision_promedio * 100:.2f}%")
print(f"Recall Promedio: {recall_promedio * 100:.2f}%")
print(f"F1-Score Promedio: {f1_score_promedio * 100:.2f}%")


Promedio general de métricas del Modelo 1 (Expresado en porcentaje):
Precisión Promedio: 5.77%
Recall Promedio: 15.54%
F1-Score Promedio: 7.42%


y recordemos el tiempo promedio de recomendacion

In [30]:
print(f"Tiempo promedio para generar recomendaciones por usuario en el Modelo 1: {tiempo_promedio_modelo_1:.4f} segundos")
print(f'Lo que equivale en milisegundos a: {tiempo_promedio_modelo_1 * 1000:.2f} ms')

Tiempo promedio para generar recomendaciones por usuario en el Modelo 1: 0.0122 segundos
Lo que equivale en milisegundos a: 12.21 ms


Ahora si podemos verificar si se cumplen los criterios de la mineria de datos

## Criterios de éxito de la minería de Datos
## **La Precision es al menos 3 veces superior a la probabilidad de acierto aleatorio?**
Anteriormente vimos que la precision promedio del modelo 1 era de aproximadamente 5.77%.
La probabilidad de acierto aleatorio es del 1%, por lo que el modelo 1 cumple con este criterio siendo 5.77% casi 6 veces superior al 1%.

## **El Recall es superior al 10%?**
Anteriormente vimos que el recall promedio del Modelo 1 era de aproximadamente 15.54%.
Por lo que el modelo cumple con este criterio de exito.

## **El F1-Score es superior al 5%?**
Anteriormente vimos que el F1-Score promedio del Modelo 1 era aproximadamente 7.42%.
Por lo que el modelo cumple con este criterio de exito.

## **El tiempo de respuesta de recomendación por usuario es inferior a 300ms?**
Anteriormente vimos que el tiempo promedio de recomendación por usuario en el Modelo 1 es de aproximadamente 12.42 ms.
Por lo que el modelo cumple con este criterio de exito.

Por lo tanto el modelo 1, cumple con todos criterios de exito.

## **Revisión de los Objetivos y Criterios de Éxito
La fase de evaluación confirma que el sistema recomendador ha superado satisfactoriamente todos los Criterios de Éxito de Minería de Datos definidos en la Fase 1, validando su capacidad para reemplazar la lógica aleatoria actual.

## Justificación del Despliegue
A pesar de la alta dispersión de los datos descripta por el comitente (un cliente compra entre 7 y 10 items), el modelo ha demostrado ser robusto. Se espera un efecto de retroalimentación positiva: al implementar el recomendador, aumentará la interacción de los usuarios con los ítems sugeridos, lo que completará la matriz usuario-ítem, disminuirá la dispersión y, por consecuencia, elevará orgánicamente la precisión del sistema a mediano plazo.

## Conclusión
El modelo es viable y lo suficientemente bueno para su despliegue.

# **6.Implementación**
Una vez validado el modelo, lo empaquetamos en una API segun lo requiere el comitente.
Recordemos que el comitente nos especifico la estructura de la API mediante el archivo **trabajoFinal.yaml**, este documento esta en formato OPEN API, es una especificación sobre como construir y consumir una API.
Esta especificación nos indica:
* Información General de la API
* Endpoints de la API 
    * `/user` (GET)
    * `/user/{userId} `(POST)
    * `/user/{userId}/recommend` (GET)
* Estructura de Datos
Utilizaremos esta archivo como guia para el diseño y contruccion de la implementación.

## Planificacion de la implementación
La implementación se realizará mediante una API REST que ofrecera las recomendaciones mediante consultas a la misma mediante el formato especificado por el comitente.
* **Infraestructura**: La API se desarrollara con el framework FAST API y se ejecutara mediante Uvicorn, 
la API se diseñara para ser ejecutado en un servidor con soporte para Python, pero el cliente puede  adaptarse el codigo para ejecutarse en un dentro de un docker.

* **Persistencia**: La base de datos se desplegará junto con la aplicación, la base de datos sera una base de datos SQLite.

**Entregables Técnicos** 
La entrega final al comitente consta de:
* **Código Fuente**:  Servicio funcional con interfaz REST según la especificación brindada.
* *Documentación de CRISP-DM**: Documentación de todo el proceso de mineria de datos, para un entendimiento profundo del proyecto.
* **Archivo README.md**: Breve descripción del sistema junto a como ejecutarlo.
* Base de datos con datos con items de ejemplo y algunos usuarios para probar.     

### Tecnologias a utilizar
Para el desarrollo de la implementación primero es necesario elegir la tecnología para la construcción de la API
* Como lenguaje usaremos Python ya que es el que hemos usado para el desarrollo del sistema recomendador, es simple de usar y tiene muchas librerías para desarrollo web.
* Usaremos la librería FastAPI para construir la API , ya que liviana,facil de usar y genera documentación automática.
* Para la base de datos usaremos SQLite, que ya hemos usado para almacenar los datos de usuarios, items y preferencias.

### Informacion general de la API
Extraemos información general de la API especificada por el comitente para agregarla a nuestra implementacion.
* Título: Sistema Recomendador - Ciencia de Datos 2025
* Descripción: API para brindar recomendaciones de ítems para un usuario.
* Versión: 1.0.0
* Contacto: gd.rottoli@gmail.com
Ahora creamos la aplicación FASTAPI

Creamos la aplicación FastAPI con la información general especificada por el comitente, especificando los datos obtenidos en el paso anterior.

In [ ]:
from fastapi import FastAPI, HTTPException, Query #Librería para crear APIs
app = FastAPI( 
    title="Sistema Recomendador - Ciencia de Datos 2025",
    description="Este es el ejemplo de la API a desarrollar para la cátedra de Ciencia de Datos, con la finalidad de brindar recomendaciones de items para un determinado usuario del sistema. A continuación se detallan los endpoints que deberán desarrollar, utilizando el lenguaje de su preferencia",
    version="1.0.0",
    contact={"email": "gd.rottoli@gmail.com"},
    openapi_tags=[{"name": "Sistema recomendador"}]
)


### Endpoints de la API
En términos sencillos, los endpoints son los puntos de contacto específicos que una API pone a disposición para que otros sistemas puedan comunicarse con ella, a partir de esos otro servicio puede utilizar las funciones de la API.
El comitente nos especifico los siguientes endpoints minimos en la especificación de la API:
* `/user` (POST): Endpoint para crear un nuevo usuario
* `/user/{userId}` (GET): Endpoint para obtener los datos de un usuario
* `/user/{userId}/recommend` (GET): Endpoint para obtener recomendaciones de items para un usuario específico
Ademas de estos, tambien consideramos necesarios los siguientes:
* `/preference` (POST): Endpoint para registrar o actualizar una preferencia de un usuario sobre un ítem
* `/preference/{userId}/{itemId}` (GET): Endpoint para obtener la preferencia de un usuario sobre un ítem específico
* `/item/{itemId}` (GET): Endpoint para obtener los datos de un ítem específico
* `/item/{itemId}` (PUT): Endpoint para actualizar un ítem existente


Antes de definir los endpoints:
1. Volvemos a definir las funciones iniciales de carga y recomendación para el sistema recomendador
2. Definimos los esquemas de datos

#### Funciones del sistema recomendador
Estas es la logica del sistema recomendador, son las funciones necesarias para que funcione el modelo elegido anteriormente.

In [ ]:
import pandas as pd #Librería para manipulación de datos
from sklearn.metrics.pairwise import cosine_similarity #Librería para cálculo de similitud del coseno
import sqlite3 #Librería para manejar bases de datos SQLite
import os #Librería para operaciones del sistema operativo
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# --- VARIABLES DE CONFIGURACIÓN ---
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
DB_NAME = 'recommendation_system.db'# Nombre del archivo de la base de datos SQLite
USERS_URL = './Datasets/Users.csv'# Ruta local del archivo CSV de usuarios
ITEMS_URL = './Datasets/Items.csv'# Ruta local del archivo CSV de items
PREFERENCES_URL = './Datasets/Preferences.csv'# Ruta local del archivo CSV de preferencias
#-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------
def load_test_data(conn):
    """Carga los datos de prueba desde los archivos CSV locales a la base de datos SQLite.
    Args: 
        conn (sqlite3.Connection): Conexión activa a la base de datos SQLite.
    """
    # Cargamos los datos desde los CSV
    users_df = pd.read_csv(USERS_URL) # Leemos el CSV de usuarios
    items_df = pd.read_csv(ITEMS_URL) # Leemos el CSV de items
    preferences_df = pd.read_csv(PREFERENCES_URL) # Leemos el CSV de preferencias
    users_df.to_sql('users', conn, if_exists='append', index=False)# Insertamos los datos de usuarios
    items_df.to_sql('items', conn, if_exists='append', index=False)# Insertamos los datos de items
    preferences_df.to_sql('preferences', conn, if_exists='append', index=False)# Insertamos los datos de preferencias

def initialize_db():
    """
    Crea e inicializa  la base de datos SOLO si el archivo DB no existe.
    """
    try:

        #Conexión a la base de datos (se crea el archivo si no existe)
        conn = sqlite3.connect(DB_NAME)
        cursor = conn.cursor()
        # Crear las tablas con el esquema definido previamente
        # Usamos esto para asegurar que los tipos de datos y restricciones (como el género) se cumplan
        cursor.executescript('''
        CREATE TABLE IF NOT EXISTS users (
            id INTEGER PRIMARY KEY,
            username TEXT NOT NULL UNIQUE,
            telephone TEXT,
            birthdate DATE,
            gender TEXT CHECK (gender IN ('F', 'M', 'X') OR gender IS NULL),
            created_at DATE
        );

        CREATE TABLE IF NOT EXISTS items (
            id INTEGER PRIMARY KEY,
            name TEXT NOT NULL,
            price REAL,
            category TEXT,
            description TEXT
        );

        CREATE TABLE IF NOT EXISTS preferences (
            user_id INTEGER,
            item_id INTEGER,
                            
            preference_value INTEGER,
            PRIMARY KEY (user_id, item_id),
            FOREIGN KEY (user_id) REFERENCES users (id),
            FOREIGN KEY (item_id) REFERENCES items (id)
        );
        ''')
        #Comentar la siguiente línea si no se desean cargar los datos de prueba
        load_test_data(conn)# Cargamos los datos de prueba desde los CSV locales
        conn.commit()# Guardamos los cambios en la base de datos
          
        print(f" Base de datos SQLite creada y cargada con éxito.")
            
    except Exception as e:
        print(f" Error al inicializar SQLite: {e}")
        raise

def initial_load():
    """Carga los datos de SQLite (una vez que la DB existe y si no, la crea) y genera las matrices necesarias para el sistema recomendador.
    Returns:
        tuple: (df, matrix_norm, user_similarity, users_df, items_df)"""
    if not(os.path.exists(DB_NAME)): # Verificamos si la base de datos ya existe
        print(f"Base de datos '{DB_NAME}' no encontrada. Creandola e inicializándola...")
        initialize_db() #Inicializa la DB si no existe
    
    #Consulta SQL para unir items y preferences
    SQL_QUERY = """
SELECT 
    T1.id as item_id,
    T1.name,
    T2.user_id,
    T2.preference_value

FROM 
    items AS T1 
INNER JOIN 
    preferences AS T2
ON 
    T1.id = T2.item_id;
"""
    
    conn = sqlite3.connect(DB_NAME)# Abrimos la conexión a la base de datos
    df = pd.read_sql_query(SQL_QUERY, conn)# Leemos las preferencias uniendo items y preferences
    users_df = pd.read_sql_query("SELECT * FROM users", conn)# Leemos los usuarios desde la base de datos
    items_df = pd.read_sql_query("SELECT * FROM items", conn)# Leemos los items desde la base de datos
    conn.close()# Cerramos la conexión a la base de datos
    #Procesamos los datos como se hizo anteriormente
    df.dropna(inplace=True)# Eliminamos filas con valores nulos
    df.drop_duplicates(subset=['item_id', 'user_id'], inplace=True) # Eliminamos filas duplicadas
    valid_user_ids = set(users_df['id'])# Obtenemos los IDs de usuarios válidos
    valid_item_ids = set(items_df['id'])# Obtenemos los IDs de items válidos
    df = df[df['user_id'].isin(valid_user_ids) & df['item_id'].isin(valid_item_ids)]# Filtramos el DataFrame (identificamos referencias inválidas)
    df = df[(df['preference_value'] >= 1) & (df['preference_value'] <= 5)]# Filtramos el DataFrame (eliminamos valores fuera de rango)
    df['item_id'] = df['item_id'].astype(int)# Convertimos la columna 'item_id' a tipo entero
    df['name'] = df['name'].astype(str)# Convertimos la columna 'name' a tipo cadena de texto
    df['user_id'] = df['user_id'].astype(int)# Convertimos la columna 'user_id' a tipo entero
    df['preference_value'] = df['preference_value'].astype(int)# Convertimos la columna 'preference_value' a tipo entero
    users_df.dropna(subset=['id'], inplace=True)# Eliminamos filas con valores nulos en las columnas 'id' 
    users_df.dropna(subset=['username'], inplace=True)# Eliminamos filas con valores nulos en la columna 'username'
    users_df.drop_duplicates(subset=['id'], inplace=True)# Eliminamos usuarios duplicados según la columna 'id'
    users_df.drop_duplicates(subset=['username'], inplace=True)# Eliminamos usuarios duplicados según la columna 'username'
    users_df['id'] = users_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
    users_df['username'] = users_df['username'].astype(str)
    users_df['telephone'] = users_df['telephone'].astype(str)# Aseguramos que la columna 'telephone' sea de tipo string
    users_df['birthdate'] = pd.to_datetime(users_df['birthdate'])# Convertimos la columna 'birthdate' a tipo datetime
    users_df['gender'] = users_df['gender'].astype(str)# seguramos que la columna 'gender' sea de tipo string
    users_df['created_at'] = pd.to_datetime(users_df['created_at'])# Convertimos la columna 'created_at' a tipo datetime
    items_df['id'].dropna(inplace=True)# Eliminamos filas con valores nulos en la columna 'id'
    items_df['id'] = items_df['id'].astype(int)# Aseguramos que la columna 'id' sea de tipo entero
    items_df['name'] = items_df['name'].astype(str)# Aseguramos que la columna 'name' sea de tipo string
    items_df['price'] = items_df['price'].astype(float)# Aseguramos que la columna 'price' sea de tipo float
    items_df['category'] = items_df['category'].astype(str)# Aseguramos que la columna 'category' sea de tipo string
    items_df['description'] = items_df['description'].astype(str)# Aseguramos que la columna 'description0' sea de tipo string

    #Creamos las matrices necesarias para el sistema recomendador
    matrix = df.pivot_table(index='user_id', columns='name', values='preference_value')# Creamos la matriz usuario-item
    user_item_matrix = matrix.copy()# hacemos una copia para trabajar sin alterar la original
    row_mean = user_item_matrix.mean(axis=1)# Calculamos el promedio por fila
    row_std = user_item_matrix.std(axis=1)# Calculamos la desviación estándar por fila
    row_std[row_std == 0] = 1 # Evitamos división por cero
    matrix_norm = user_item_matrix.sub(row_mean, axis=0).div(row_std, axis=0)# Normalizamos la matriz usuario-item
    user_item_matrix_filled = matrix_norm.fillna(0)# Rellenamos los valores NaN con 0 para calcular similitudes
    user_similarity_cosine = cosine_similarity(user_item_matrix_filled)# Calculamos la similitud del coseno entre los usuarios
    user_ids = user_item_matrix_filled.index.tolist()# Obtenemos los IDs de usuario
    user_similarity = pd.DataFrame( #Creamos la matriz de similitud de usuarios
        user_similarity_cosine, 
        index=user_ids, 
        columns=user_ids
    )
    user_similarity.index = user_similarity.index.astype(str)# Aseguramos que los índices sean strings
    user_similarity.columns = user_similarity.columns.astype(str)# Aseguramos que las columnas sean strings
    # Retornamos los datos procesados
    return df, matrix_norm, user_similarity, users_df, items_df,row_mean

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# --- Carga y precálculo de datos al inicio del servidor ---
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
try:
    DF, MATRIX_NORM, USER_SIMILARITY, USERS_DF, ITEMS_DF = initial_load()#
except Exception as e:# Manejo de errores en la carga inicial
    print(f" ERROR FATAL: La aplicación no pudo iniciar debido al error de carga/procesamiento: {e}")

#---------------------------------------------------------------------------------------------------------------------------------------------------------------------------
# --- LÓGICA DE RECOMENDACIÓN ---
#--------------------------------------------------------------------------------------------------------------------------------------------------------------------------
def user_has_preferences(user_id: int) -> bool:
    """Verifica si un usuario tiene preferencias registradas en la matriz normalizada.
    Args:a
        user_id (int): ID del usuario a verificar.
    Returns:
        bool: True si el usuario tiene preferencias, False en caso contrario."""
    return user_id in MATRIX_NORM.index

def cold_start_items_recommendations(number_max_of_recommendations: int) -> list: 
    """Genera recomendaciones para usuarios nuevos basadas en los items más populares.
    Args:
        number_max_of_recommendations (int): Número máximo de items a recomendar.
    Returns: 
        list: Lista de nombres de items recomendados."""
    top_items = DF.groupby('name')['preference_value'].count().sort_values(ascending=False)# Contamos la cantidad de preferencias por item y los ordenamos
    return top_items.head(number_max_of_recommendations).index.tolist()# Retornamos los nombres de los items más populares

def get_recommendations(user_id: int, number_max_of_recommendations: int) -> list:
    """Genera recomendaciones para un usuario específico, ya sea basado en usuarios similares o en los items más populares si el usuario es nuevo.
    Args:
        user_id (int): ID del usuario para el cual se generan recomendaciones.
        number_max_of_recommendations (int): Número máximo de items a recomendar.
    Returns:
        list: Lista de nombres de items recomendados.
    """
    if user_has_preferences(user_id): # Usuario existente con preferencias
        user_id_str = str(user_id)# Convertimos a string para coincidir con los índices del DataFrame
        user_items = MATRIX_NORM.loc[user_id]# Obtenemos las preferencias del usuario
        items_comprados = user_items[user_items.notna()].index.tolist()# Items comprados por el usuario

        similar_users = ( # Obtenemos usuarios similares
            USER_SIMILARITY[user_id_str]
            .sort_values(ascending=False)
            .drop(user_id_str, errors='ignore')
            .head(number_max_of_recommendations)
        )
        similar_users_ids = similar_users.index.astype(int).tolist()# IDs de usuarios similares 
        sum_similarity = similar_users.sum()
        if similar_users.empty or sum_similarity == 0:# No hay usuarios similares
            return cold_start_items_recommendations(number_max_of_recommendations)# Recomendaciones por popularidad
        similar_user_preferences = MATRIX_NORM.loc[similar_users_ids]# Preferencias de usuarios similares
        items_comprados_por_similares = similar_user_preferences.columns[
            similar_user_preferences.notna().any()
        ].tolist()
        candidate_items = list(set(items_comprados_por_similares) - set(items_comprados))# Items candidatos para recomendar
        if not candidate_items:# No hay items candidatos
            return cold_start_items_recommendations(number_max_of_recommendations)# Recomendaciones por popularidad
        candidate_matrix = similar_user_preferences[candidate_items].copy()# Matriz de items candidatos
        weighted_scores = candidate_matrix.multiply(similar_users, axis=0)# Puntuaciones ponderadas
        recommendation_scores = weighted_scores.sum(axis=0) / sum_similarity# Puntuaciones finales
        recomendaciones_ordenadas = recommendation_scores.sort_values(ascending=False)# Ordenamos las recomendaciones
        return recomendaciones_ordenadas.head(number_max_of_recommendations).index.tolist()# Retornamos los nombres de los items recomendados
    else:
        # Usuario nuevo sin preferencias
        return cold_start_items_recommendations(number_max_of_recommendations)# Recomendaciones por popularidad


#### Estructura de datos
Definimos los modelos de datos para la API, esto es necesario para validación y documentación
Aqui definimos todas las clases del modelo necesarias para el funcionamiento de la API. 
Nos basamos en la especificación del comitente.


In [ ]:
class UserAttributes(BaseModel):
    """ Modelo de atributos del usuario"""
    # Atributos del usuario basados, optional significa que pueden estar ausentes en la solicitud
    telephone: Optional[str] = None
    birthdate: Optional[date] = None
    gender: Optional[str] = None
    created_at: Optional[date] = None
    
    # Configuración para permitir campos extra y excluir nulos en la serialización
    model_config = ConfigDict(extra="allow", exclude_none=True)

class User(BaseModel):
    """ Modelo de usuario"""
    id: int
    username: str
    attributes: UserAttributes = UserAttributes()

class ItemAttributes(BaseModel):
    """ Modelo de atributos del ítem"""
    # Atributos del ítem, optional significa que pueden estar ausentes en la solicitud
    price: Optional[float] = None
    category: Optional[str] = None
    description: Optional[str] = None
    # Configuración para permitir campos extra y excluir nulos en la serialización
    model_config = ConfigDict(extra="allow", exclude_none=True)

class Item(BaseModel):
    """ Modelo de ítem"""
    id: int
    name: str
    attributes: ItemAttributes = ItemAttributes()

class ItemArray(BaseModel):
    """ Modelo para lista de ítems"""
    items: List[Item]

class Preference(BaseModel):
    """ Modelo de preferencia de usuario sobre un ítem"""
    user_id: int
    item_id: int
    # La validación preference_value (1 a 5)
    preference_value: Annotated[
        int, 
        Field(
            ge=1, 
            le=5, 
            description="El valor de la preferencia debe ser un entero entre 1 y 5."
        )
    ]


#### Endpoints minimos
Ahora si estamos listos para definir los endpoints minimos requeridos.
Recordemos que estos son los endpoints obligatorios especificados por el comitente, son los endpoints para crear un usuario, obtener un usuario y obtener recomendaciones para un usuario.


In [ ]:
# Endpoint: /user (POST)
# Endpoint para crear un nuevo usuario
@app.post("/user", response_model=User, tags=["Sistema recomendador"])
def create_user(user: User):
    """
    Inserta un nuevo usuario en la base de datos.
    """
    try:
        with sqlite3.connect(DB_NAME) as conn:
            cursor = conn.cursor()
            
            # Extraemos los datos básicos y los atributos
            # Usamos model_dump para obtener los valores del modelo UserAttributes
            attr = user.attributes
            
            # Preparamos la consulta SQL
            insert_query = """
                INSERT INTO users (id, username, telephone, birthdate, gender, created_at) 
                VALUES (?, ?, ?, ?, ?, ?);
            """
            
            # Mapeamos los valores 
            values = (
                user.id,
                user.username,
                attr.telephone,
                attr.birthdate.isoformat() if attr.birthdate else None,
                attr.gender,
                attr.created_at.isoformat() if attr.created_at else None
            )
            # Ejecutamos la inserción
            cursor.execute(insert_query, values)
            # Guardamos los cambios
            conn.commit() 
        return user
    # Manejo de errores específicos de SQLite
    except sqlite3.IntegrityError as e:
        # Error de ID duplicado o Violación de restricción
        raise HTTPException(
            status_code=400, 
            detail={"code": "INTEGRITY_ERROR", "message": f"Error de integridad en DB: {e}"}
        )
    # Manejo de otros errores
    except Exception as e:
        raise HTTPException(
            status_code=500, 
            detail={"code": "DB_ERROR", "message": f"Error al crear usuario: {e}"}
        )

# Endpoint: /user/{userId} (GET)
# Endpoint para obtener los datos de un usuario
@app.get("/user/{userId}", response_model=User, tags=["Sistema recomendador"])
def get_user(userId: int):
    """ Obtiene los datos de un usuario especifico"""
    try:
        with sqlite3.connect(DB_NAME) as conn:
            conn.row_factory = sqlite3.Row 
            cursor = conn.cursor()
            # Realizamos la consulta para obtener los datos del usuario
            query = "SELECT id, username, telephone, birthdate, gender, created_at FROM users WHERE id = ?"
            cursor.execute(query, (userId,))
            # Obtenemos la fila resultante
            row = cursor.fetchone()
        # Si no se encuentra el usuario, retornamos un error 404
        if row is None:
            raise HTTPException(status_code=404, detail={"code": "USER_NOT_FOUND", "message": "..."})
        # Convertimos la fila a un diccionario para facilitar el acceso
        user_dict = dict(row)

        # Función auxiliar para convertir fechas de forma segura
        def safe_parse_date(date_val):
            if date_val is None or date_val == "":
                return None
            return pd.to_datetime(date_val).date()

        # Construimos los atributos del usuario
        attributes = UserAttributes(
            telephone=user_dict.get('telephone'),
            birthdate=safe_parse_date(user_dict.get('birthdate')), # <-- Limpieza aquí
            gender=user_dict.get('gender'),
            created_at=safe_parse_date(user_dict.get('created_at')) # <-- Limpieza aquí
        )
        # Construimos y retornamos el User
        return User(
            id=user_dict['id'],
            username=user_dict['username'],
            attributes=attributes
        )
    # Manejo de errores
    except Exception as e:
        # Esto te ayudará a ver qué valor exacto falló si hay otro error
        raise HTTPException(status_code=500, detail={"code": "DB_ERROR", "message": str(e)})
    
# Endpoint: /user/{userId}/recommend (GET)
# Endpoint para obtener recomendaciones de items para un usuario específico
@app.get("/user/{userId}/recommend", response_model=ItemArray, tags=["Sistema recomendador"])
def recommend_items(userId: int, n: int = Query(5, description="Número de items a recomendar.", ge=1, le=50)):
    """
    Genera recomendaciones de items para un usuario específico utilizando filtro colaborativo basado en usuarios similares.
    """
    # Verificamos existencia del usuario 
    with sqlite3.connect(DB_NAME) as conn:
        user_check = conn.execute("SELECT 1 FROM users WHERE id = ?", (userId,)).fetchone()
    # Si el usuario no existe, retornamos un error 404
    if not user_check:
        raise HTTPException(
            status_code=404, 
            detail={"code": "USER_NOT_FOUND", "message": f"User {userId} not found"}
        )

    try:
        # Obtenemos los nombres de los ítems recomendados
        recommended_item_names = get_recommendations(userId, n)
        
        # Filtramos el DataFrame de items para obtener los detalles de los ítems recomendados
        recommended_df = ITEMS_DF[ITEMS_DF['name'].isin(recommended_item_names)]
        # Construimos la lista de objetos Item para la respuesta
        item_objects = []
        for _, row in recommended_df.iterrows():
            #  Construimos los atributos del ítem
            item_attrs = ItemAttributes(
                price=row.get('price'),
                category=row.get('category'),
                description=row.get('description')
            )
            
            # Construimos el Item 
            item_objects.append(Item(
                id=int(row['id']),
                name=str(row['name']),
                attributes=item_attrs
            ))
        # Retornamos la lista de ítems recomendados
        return ItemArray(items=item_objects)
    # Manejo de errores
    except Exception as e:
        print(f"Error interno en recomendación para el usuario {userId}: {e}")
        raise HTTPException(
            status_code=500, 
            detail={"code": "INTERNAL_ERROR", "message": f"Error al generar recomendaciones: {e}"}
        )
    

#### Endpoints complementarios
Ahora tambien definimos los endpoints que tambien consideramos útiles para la API del sistema recomendador. Decidimos definir estos endpoints ya que los consideramos necesarios para tener un mayor control sobre el sistema.


In [ ]:
# Endpoint: /preference (POST)
# Endpoint para registrar o actualizar una preferencia de un usuario sobre un ítem
@app.post("/preference", tags=["Sistema recomendador"])
def create_preference(preference: Preference):
    """
    Registra o actualiza una preferencia de un usuario sobre un ítem.
    """
    global DF, MATRIX_NORM, USER_SIMILARITY, USERS_DF, ITEMS_DF, ROW_MEAN
    
    try:
        with sqlite3.connect(DB_NAME) as conn:
            # Verificamos el usuario
            user_exists = conn.execute("SELECT 1 FROM users WHERE id = ?", (preference.user_id,)).fetchone()
            if not user_exists:
                raise HTTPException(status_code=404, detail={"code": "USER_NOT_FOUND", "message": f"ID {preference.user_id} no existe"})
            # Verificamos el ítem 
            item_exists = conn.execute("SELECT 1 FROM items WHERE id = ?", (preference.item_id,)).fetchone()
            if not item_exists:
                raise HTTPException(status_code=404, detail={"code": "ITEM_NOT_FOUND", "message": f"ID {preference.item_id} no existe"})
            # Insertamos o actualizamos la preferencia
            insert_query = """
            INSERT INTO preferences (user_id, item_id, preference_value) 
            VALUES (?, ?, ?) 
            ON CONFLICT(user_id, item_id) DO UPDATE SET 
                preference_value = excluded.preference_value;
            """
            # Ejecutamos la consulta
            conn.execute(insert_query, (preference.user_id, preference.item_id, preference.preference_value))
            # guardamos los cambios
            conn.commit()

        # RECALCULAR MATRICES 
        DF, MATRIX_NORM, USER_SIMILARITY, USERS_DF, ITEMS_DF, ROW_MEAN = initial_load()
        
        return {"code": "SUCCESS", "message": "Preferencia guardada y motor de recomendaciones actualizado"}
    # Manejo de errores
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500, 
            detail={"code": "DB_ERROR", "message": f"Error: {str(e)}"}
        )

# Endpoint: /preference/{userId}/{itemId} (GET)
# Endpoint para obtener la preferencia de un usuario sobre un ítem específico
@app.get("/preference/{userId}/{itemId}", response_model=Preference, tags=["Sistema recomendador"])
def get_preference(userId: int, itemId: int):
    """
    Obtiene la preferencia  de un usuario sobre un ítem específico.
    """
    try:
        with sqlite3.connect(DB_NAME) as conn:
            # Usamos Row para acceder por nombre de columna
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            # Realizamos la consulta SQL
            query = "SELECT user_id, item_id, preference_value FROM preferences WHERE user_id = ? AND item_id = ?"
            cursor.execute(query, (userId, itemId))
            row = cursor.fetchone()
        # Verificamos si se encontró la preferencia
        if row is None:
            raise HTTPException(
                status_code=404, 
                detail={
                    "code": "PREFERENCE_NOT_FOUND", 
                    "message": f"No se encontró preferencia del usuario {userId} para el ítem {itemId}"
                }
            )

        # Mapeo directo al modelo Preference
        return Preference(
            user_id=row['user_id'],
            item_id=row['item_id'],
            preference_value=row['preference_value']
        )
    # Manejo de errores
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500, 
            detail={"code": "DB_ERROR", "message": f"Error al consultar preferencia: {str(e)}"}
        )

# Endpoint: /item/{itemId} (GET)
# Endpoint para obtener los datos de un ítem específico
@app.get("/item/{itemId}", response_model=Item, tags=["Sistema recomendador"])
def get_item(itemId: int):
    """
    Obtener los datos de un ítem.
    """
    try:
        with sqlite3.connect(DB_NAME) as conn:
            # Usamos Row para acceder por nombre de columna
            conn.row_factory = sqlite3.Row
            cursor = conn.cursor()
            
            # Realizamos la consulta SQL
            query = "SELECT id, name, price, category, description FROM items WHERE id = ?"
            cursor.execute(query, (itemId,))
            row = cursor.fetchone()
        # Verificamos si se encontró el ítem
        if row is None:
            raise HTTPException(
                status_code=404, 
                detail={"code": "ITEM_NOT_FOUND", "message": f"Item {itemId} no encontrado"}
            )

        # Convertimos la fila a diccionario
        item_dict = dict(row)

        # Mapeamos las columnas planas al modelo ItemAttributes
        attributes = ItemAttributes(
            price=item_dict.get('price'),
            category=item_dict.get('category'),
            description=item_dict.get('description')
        )

        # Retornamos el objeto Item estructurado
        return Item(
            id=item_dict['id'],
            name=item_dict['name'],
            attributes=attributes
        )
    # Manejo de errores
    except Exception as e:
        raise HTTPException(
            status_code=500, 
            detail={"code": "DB_ERROR", "message": f"Error al obtener ítem: {str(e)}"}
        )

# Endpoint: /item/{itemId} (PUT)
# Endpoint para actualizar un ítem existente
@app.put("/item/{itemId}", response_model=Item, tags=["Sistema recomendador"])
def update_item(itemId: int, item: Item):
    """
    Actualizar el nombre y los atributos (precio, categoría, descripción) de un ítem.
    """
    global DF, MATRIX_NORM, USER_SIMILARITY, USERS_DF, ITEMS_DF, ROW_MEAN
    
    try:
        with sqlite3.connect(DB_NAME) as conn:
            cursor = conn.cursor()
            
            # Extraemos los atributos del ítem
            attr = item.attributes
            
            # Preparamos la consulta de actualización
            update_query = """
            UPDATE items 
            SET name = ?, price = ?, category = ?, description = ?
            WHERE id = ?
            """
            
            # Ejecutamos la actualización
            cursor.execute(update_query, (
                item.name, 
                attr.price, 
                attr.category, 
                attr.description, 
                itemId
            ))
            
            if cursor.rowcount == 0:
                raise HTTPException(
                    status_code=404, 
                    detail={"code": "ITEM_NOT_FOUND", "message": f"Ítem {itemId} no encontrado para actualizar"}
                )
            
            conn.commit()

        # RECALCULAR MATRICES
        # Esto asegura que el sistema recomendador use el nuevo nombre/precio inmediatamente
        DF, MATRIX_NORM, USER_SIMILARITY, USERS_DF, ITEMS_DF, ROW_MEAN = initial_load()
            
        item.id = itemId
        return item
        
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=500, 
            detail={"code": "DB_ERROR", "message": f"Error al actualizar ítem: {str(e)}"}
        )
    

### Ejecución
Ya estaria terminado el código de la API para el sistema recomendador.
El codigo completo de la API se encuentra en el archivo **API.py**.
Los pasos para la ejecucion de la api se encuentran dentro del archivo **README.md**

## Planificación de monitoreo y control del rendimiento
Para garantizar que el sistema recomendador mantenga al menos el rendimiento observado durante la evaluación, se establecen las siguientes actividades de control:
### 1.Actividades de monitoreo de rendimiento
*   Actualmente cada cliente compra entre 7 y 10 items, Semanalmente  calcularemos el promedio de items comprados por cliente, para ver si el sistema tiene un impacto en el aspecto de aumentar las ventas.
*   Semanalmente evaluaremos el sistema con la funcion evaluate_model, pero con los nuevos datos recolectados. 
Si las metricas promedio caen por debajo de los valores minimos definidos en los criterio de éxito esto representaria una degradación del modelo.
*   Semanalmente calcularemos el promedio de tiempo de respuesta de recomendación, un aumento por encima del valor maximo definido el los criterios de exito, esto representaria una sobrecarga en la base de datos por el crecimiento de la tabla de preferencias.

### 2.Detección de degradación
La performance puede reducirse por:
*   Los usuarios cambian de gustos, pero el modelo sigue recomendando lo mismo basándose en datos viejos.
*   El sistema no tiene nada nuevo que ofrecer, porque eñ usuario ya compró todos ítems o todos los que podrian interesarles.

### 3.Plan de acción ante pérdida de rendimiento
En caso de detectar que las métricas caen por debajo de los criterios de éxito, se ejecutarán las siguientes acciones:
*   **Reentrenamiento:**
    Si la precisión baja, se forzará una actualización completa de las matrices USER_SIMILARITY y MATRIX_NORM con el 100% de los datos.
*   **Ajuste de parámetros:**
    Si lo anterior no basta,se evaluará aumentar el número de usuarios similares.

En el caso de detectar que el tiempo de respuesta es muy alto, puede implementar una capa de cache que almacene temporalmente las recomendaciones para un usuario de modo que reduzca el tiempo de repuestas para usuarios frecuentes.


## Informe Final
El proyecto consistió en el diseño, desarrollo y validación de un sistema recomendador de filtro colaborativo basado en usuarios que permita generar recomendaciones personalizadas de productos para cada usuario. 
El sistema reemplaza el carrusel aleatorio actual por una solución predictiva capaz de personalizar la recomendación de productos para un usuario determinado basada en las preferencias de usuarios similares. 
El objetivo del negocio es un incremento del 10% en las ventas proyectado para 2026, respecto al año anterior.
Se determino que nuestra solución es lo suficiente buena, ya que supero los criterios de éxito de minería de datos definidos en los objetivos de la misma y se espera que la personalización de las recomendaciones tenga un impacto directo sobre las ventas y permita alcanzar el objetivo del negocio.
