openapi: 3.0.4
info:
  title: Sistema Recomendador - Ciencia de Datos 2025
  description: |-
    Este es el ejemplo de la API a desarrollar para la cátedra de Ciencia de Datos, con la finalidad de brindar recomendaciones de items para un determinado usuario del sistema. 
    A continuación se detallan los endpoints que deberán desarrollar, utilizando el lenguaje de su preferencia
  contact:
    email: gd.rottoli@gmail.com
  version: 1.0.0
tags:
  - name: Sistema recomendador
paths:
  /user:
    post:
      tags:
        - Sistema recomendador
      summary: Crear usuario.
      description: Insertar un nuevo usuario a la base de datos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /user/{userId}:
    get:
      tags:
        - Sistema recomendador
      summary: Obtener usuario.
      description: Obtener los datos del usuario
      parameters:
        - name: userId
          in: path
          description: ID del usuario
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
                
  /user/{userId}/recommend:
    get:
      tags:
        - Sistema recomendador
      summary: Recomendar
      description: Obtener n recomendaciones para un usuario determinado
      parameters:
        - name: userId
          in: path
          description: ID del usuario
          required: true
          schema:
            type: integer
            format: int64
        - name: n
          in: query
          description: numero de items a recomendar. 
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ItemArray'
        '400':
          description: Invalid ID supplied
        '404':
          description: User not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: pepitaLaPistolera
        attributes:
          type: object
          example: {
            'field1': 'value1',
            'field2': 'value2'
          }
    Item:
      type: object
      properties:
        id: 
          type: integer
          format: int64
          example: 42
        name:
          type: string
          example: Las mil y una noches
        attributes:
          type: object
          example: {
            'field1': 'value1',
            'field2': 'value2'
          }
    ItemArray:
      type: object
      properties: 
        items:
          type: array
          items:
            $ref: '#/components/schemas/Item'
      
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
  requestBodies:
    User:
      description: User que necesita ser agregado a la base de datos
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'

  